### ISSUE TITLE
UnboundLocalError: local variable 'res' referenced before assignment

### ISSUE THREAD

**Issue by netdevfighter** [Yubico/yubikey-manager#11]
I get an sporadically error/stacktrace after multiple use of the command "ykman slot calculate -T 2". Have you any ideas why?

Python Version: 3.6.0
OS: macOS 10.12.3

```
➜  ~ ykman -v      
YubiKey Manager (ykman) version: 0.3.1
Libraries:
    libykpers 1.17.3
    libu2f-host 1.1.3
    libusb 1.0.21
➜  ~ ykman slot calculate -T 2
Touch your YubiKey...
722158
➜  ~ ykman slot calculate -T 2
Touch your YubiKey...
722158
➜  ~ ykman slot calculate -T 2
Touch your YubiKey...
Traceback (most recent call last):
  File "/usr/local/bin/ykman", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/ykman/cli/__main__.py", line 116, in main
    cli(obj={})
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/ykman/cli/slot.py", line 359, in calculate
    click.echo(res)
UnboundLocalError: local variable 'res' referenced before assignment
```

**Comment by dagheyman** [comment]
I can only reproduce the error by removing the YubiKey from the USB port while it is prompting for touch. [Here](https://github.com/Yubico/yubikey-manager/blob/master/ykman/cli/slot.py#L359) is the code that is crashing. The error could of course be handled prettier (like a "something went wrong" message), but I'm not sure what the root cause is.
```
$ ykman slot calculate -T 1
Touch your YubiKey...
Traceback (most recent call last):
  File "/usr/local/bin/ykman", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/ykman/cli/__main__.py", line 116, in main
    cli(obj={})
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/ykman/cli/slot.py", line 360, in calculate
    click.echo(res)
UnboundLocalError: local variable 'res' referenced before assignment
```

**Comment by dainnilsson** [comment]
The error handling does look wrong though. The inner try catches the error, but if the error code isn't 4, it falls though to .echo(res) (which is undefined). it should give you a nicer error based on the error code from ykpers.

**Comment by netdevfighter** [comment]
Okay, I have tried it with three different USB ports and the problem was always the same.  

1. usb port on the left side of the mac
1. usb port on the right side of the mac
1. usb hub port on dell monitor

**Comment by dagheyman** [comment]
Could you post the output of `ykman info` so we can see what YubiKey model and firmware version you have?

**Comment by netdevfighter** [comment]
Yes, I can :) 
```
➜  bin ykman info
Device name: YubiKey NEO
Serial number: 4872178
Firmware version: 3.4.9
Enabled connection(s): OTP+U2F+CCID

Device capabilities:
    OTP:	Enabled
    U2F:	Enabled
    CCID:	Enabled
    OPGP:	Enabled
    PIV:	Enabled
    OATH:	Enabled
```
