### ISSUE TITLE
yubikey-manager-0.7.0: tests fail due to missing test/util.py

### ISSUE THREAD

**Issue by gktrk** [Yubico/yubikey-manager#111]
The source tarball (https://github.com/Yubico/yubikey-manager/releases/download/yubikey-manager-0.7.0/yubikey-manager-0.7.0.tar.gz) is missing `test/util.py` which leads to the following test failure:

```
$ touch test/__init__.py

$ python setup.py test
running test
running egg_info
writing top-level names to yubikey_manager.egg-info/top_level.txt
writing yubikey_manager.egg-info/PKG-INFO
writing entry points to yubikey_manager.egg-info/entry_points.txt
writing requirements to yubikey_manager.egg-info/requires.txt
writing dependency_links to yubikey_manager.egg-info/dependency_links.txt
reading manifest file 'yubikey_manager.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'ChangeLog'
warning: no files found matching 'resources/*'
writing manifest file 'yubikey_manager.egg-info/SOURCES.txt'
running build_ext
test_credential_data_make_key (test.test_oath.TestOathFunctions) ... ok
test_credential_parse_issuer_and_name (test.test_oath.TestOathFunctions) ... ok
test_credential_parse_only_name (test.test_oath.TestOathFunctions) ... ok
test_credential_parse_period_and_issuer_and_name (test.test_oath.TestOathFunctions) ... ok
test_credential_parse_period_and_name (test.test_oath.TestOathFunctions) ... ok
test_credential_parse_wierd_issuer_and_name (test.test_oath.TestOathFunctions) ... ok
test_derive_key (test.test_oath.TestOathFunctions) ... ok
test_parse_uri (test.test_oath.TestOathFunctions) ... ok
test_parse_uri_issuer (test.test_oath.TestOathFunctions) ... ok
test_with_as_closes_driver (test.test_device.TestDevice) ... ok
test_with_as_reraises_exception (test.test_device.TestDevice) ... ok
test_with_closes_driver (test.test_device.TestDevice) ... ok
test_with_reraises_exception (test.test_device.TestDevice) ... ok
test_cli_config (unittest.loader._FailedTest) ... ERROR
test_cli_misc (unittest.loader._FailedTest) ... ERROR
test_piv (unittest.loader._FailedTest) ... ERROR
util (unittest.loader._FailedTest) ... ERROR
test_cli_oath (unittest.loader._FailedTest) ... ERROR
test_cli_openpgp (unittest.loader._FailedTest) ... ERROR
test_cli_otp (unittest.loader._FailedTest) ... ERROR
test_de_layout (test.test_scancodes.TestScanMap) ... ok
test_us_layout (test.test_scancodes.TestScanMap) ... ok
test_util (unittest.loader._FailedTest) ... ERROR
test_generate_random_management_key (test.test_piv.TestPivFunctions) ... ok
test_external_libs (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cli_config (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cli_config
Traceback (most recent call last):
  File "/usr/lib64/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/yubikey-manager-0.7.0/test/on_yubikey/test_cli_config.py", line 2, in <module>
    from .util import (DestructiveYubikeyTestCase, ykman_cli, can_write_config)
  File "/tmp/yubikey-manager-0.7.0/test/on_yubikey/util.py", line 9, in <module>
    import test.util
ImportError: No module named 'test.util'


======================================================================
ERROR: test_cli_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cli_misc
Traceback (most recent call last):
  File "/usr/lib64/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/yubikey-manager-0.7.0/test/on_yubikey/test_cli_misc.py", line 1, in <module>
    from .util import (DestructiveYubikeyTestCase, ykman_cli)
  File "/tmp/yubikey-manager-0.7.0/test/on_yubikey/util.py", line 9, in <module>
    import test.util
ImportError: No module named 'test.util'


======================================================================
ERROR: test_piv (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_piv
Traceback (most recent call last):
  File "/usr/lib64/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/yubikey-manager-0.7.0/test/on_yubikey/test_piv.py", line 11, in <module>
    from .util import (
  File "/tmp/yubikey-manager-0.7.0/test/on_yubikey/util.py", line 9, in <module>
    import test.util
ImportError: No module named 'test.util'


======================================================================
ERROR: util (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: util
Traceback (most recent call last):
  File "/usr/lib64/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/yubikey-manager-0.7.0/test/on_yubikey/util.py", line 9, in <module>
    import test.util
ImportError: No module named 'test.util'


======================================================================
ERROR: test_cli_oath (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cli_oath
Traceback (most recent call last):
  File "/usr/lib64/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/yubikey-manager-0.7.0/test/on_yubikey/test_cli_oath.py", line 3, in <module>
    from .util import (DestructiveYubikeyTestCase, missing_mode, ykman_cli)
  File "/tmp/yubikey-manager-0.7.0/test/on_yubikey/util.py", line 9, in <module>
    import test.util
ImportError: No module named 'test.util'


======================================================================
ERROR: test_cli_openpgp (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cli_openpgp
Traceback (most recent call last):
  File "/usr/lib64/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/yubikey-manager-0.7.0/test/on_yubikey/test_cli_openpgp.py", line 3, in <module>
    from .util import (DestructiveYubikeyTestCase, missing_mode, ykman_cli)
  File "/tmp/yubikey-manager-0.7.0/test/on_yubikey/util.py", line 9, in <module>
    import test.util
ImportError: No module named 'test.util'


======================================================================
ERROR: test_cli_otp (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cli_otp
Traceback (most recent call last):
  File "/usr/lib64/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/yubikey-manager-0.7.0/test/on_yubikey/test_cli_otp.py", line 32, in <module>
    from .util import (DestructiveYubikeyTestCase, missing_mode, ykman_cli)
  File "/tmp/yubikey-manager-0.7.0/test/on_yubikey/util.py", line 9, in <module>
    import test.util
ImportError: No module named 'test.util'


======================================================================
ERROR: test_util (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_util
Traceback (most recent call last):
  File "/usr/lib64/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/yubikey-manager-0.7.0/test/test_util.py", line 7, in <module>
    from .util import open_file
ImportError: No module named 'test.util'


======================================================================
ERROR: test_external_libs (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_external_libs
Traceback (most recent call last):
  File "/usr/lib64/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/yubikey-manager-0.7.0/test/test_external_libs.py", line 3, in <module>
    from test.util import ykman_cli
ImportError: No module named 'test.util'


----------------------------------------------------------------------
Ran 25 tests in 0.018s

FAILED (errors=9)
Test failed: <unittest.runner.TextTestResult run=25 errors=9 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=25 errors=9 failures=0>
```

Adding the file from the git repo fixes the issue:

```
$ cat yubikey-manager-0.7.0-fix-tests.patch 
diff --git b/test/util.py a/test/util.py
new file mode 100644
index 0000000..0551d06
--- /dev/null
+++ a/test/util.py
@@ -0,0 +1,18 @@
+from click.testing import CliRunner
+from ykman.cli.__main__ import cli
+import os
+
+
+PKG_DIR = os.path.dirname(os.path.abspath(__file__))
+
+
+def open_file(*relative_path):
+    return open(os.path.join(PKG_DIR, 'files', *relative_path), 'rb')
+
+
+def ykman_cli(*argv, **kwargs):
+    runner = CliRunner()
+    result = runner.invoke(cli, list(argv), obj={}, **kwargs)
+    if result.exit_code != 0:
+        raise result.exception
+    return result.output

$ patch -p1 < yubikey-manager-0.7.0-fix-tests.patch 
patching file test/util.py

$ python setup.py test
running test
running egg_info
writing yubikey_manager.egg-info/PKG-INFO
writing dependency_links to yubikey_manager.egg-info/dependency_links.txt
writing entry points to yubikey_manager.egg-info/entry_points.txt
writing requirements to yubikey_manager.egg-info/requires.txt
writing top-level names to yubikey_manager.egg-info/top_level.txt
reading manifest file 'yubikey_manager.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'ChangeLog'
warning: no files found matching 'resources/*'
writing manifest file 'yubikey_manager.egg-info/SOURCES.txt'
running build_ext
test_credential_data_make_key (test.test_oath.TestOathFunctions) ... ok
test_credential_parse_issuer_and_name (test.test_oath.TestOathFunctions) ... ok
test_credential_parse_only_name (test.test_oath.TestOathFunctions) ... ok
test_credential_parse_period_and_issuer_and_name (test.test_oath.TestOathFunctions) ... ok
test_credential_parse_period_and_name (test.test_oath.TestOathFunctions) ... ok
test_credential_parse_wierd_issuer_and_name (test.test_oath.TestOathFunctions) ... ok
test_derive_key (test.test_oath.TestOathFunctions) ... ok
test_parse_uri (test.test_oath.TestOathFunctions) ... ok
test_parse_uri_issuer (test.test_oath.TestOathFunctions) ... ok
test_with_as_closes_driver (test.test_device.TestDevice) ... ok
test_with_as_reraises_exception (test.test_device.TestDevice) ... ok
test_with_closes_driver (test.test_device.TestDevice) ... ok
test_with_reraises_exception (test.test_device.TestDevice) ... ok
test_set_lock_code (test.on_yubikey.test_cli_config.TestConfigLockCode) ... skipped 'Device can not write config'
test_disable_all (test.on_yubikey.test_cli_config.TestConfigNFC) ... skipped 'Device can not write config'
test_disable_and_enable (test.on_yubikey.test_cli_config.TestConfigNFC) ... skipped 'Device can not write config'
test_disable_fido2 (test.on_yubikey.test_cli_config.TestConfigNFC) ... skipped 'Device can not write config'
test_disable_oath (test.on_yubikey.test_cli_config.TestConfigNFC) ... skipped 'Device can not write config'
test_disable_openpgp (test.on_yubikey.test_cli_config.TestConfigNFC) ... skipped 'Device can not write config'
test_disable_otp (test.on_yubikey.test_cli_config.TestConfigNFC) ... skipped 'Device can not write config'
test_disable_piv (test.on_yubikey.test_cli_config.TestConfigNFC) ... skipped 'Device can not write config'
test_disable_u2f (test.on_yubikey.test_cli_config.TestConfigNFC) ... skipped 'Device can not write config'
test_disable_all (test.on_yubikey.test_cli_config.TestConfigUSB) ... skipped 'Device can not write config'
test_disable_and_enable (test.on_yubikey.test_cli_config.TestConfigUSB) ... skipped 'Device can not write config'
test_disable_fido2 (test.on_yubikey.test_cli_config.TestConfigUSB) ... skipped 'Device can not write config'
test_disable_oath (test.on_yubikey.test_cli_config.TestConfigUSB) ... skipped 'Device can not write config'
test_disable_openpgp (test.on_yubikey.test_cli_config.TestConfigUSB) ... skipped 'Device can not write config'
test_disable_otp (test.on_yubikey.test_cli_config.TestConfigUSB) ... skipped 'Device can not write config'
test_disable_piv (test.on_yubikey.test_cli_config.TestConfigUSB) ... skipped 'Device can not write config'
test_disable_u2f (test.on_yubikey.test_cli_config.TestConfigUSB) ... skipped 'Device can not write config'
test_mode_command (test.on_yubikey.test_cli_config.TestConfigUSB) ... skipped 'Device can not write config'
test_ykman_info (test.on_yubikey.test_cli_misc.TestYkmanInfo) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_delete_certificate_requires_authentication (test.on_yubikey.test_piv.KeyManagement) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_generate_csr_works (test.on_yubikey.test_piv.KeyManagement) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_generate_key_requires_authentication (test.on_yubikey.test_piv.KeyManagement) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_generate_self_signed_certificate_requires_authentication (test.on_yubikey.test_piv.KeyManagement) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_generate_self_signed_certificate_slot_9a_works (test.on_yubikey.test_piv.KeyManagement) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_generate_self_signed_certificate_slot_9c_works (test.on_yubikey.test_piv.KeyManagement) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_import_certificate_requires_authentication (test.on_yubikey.test_piv.KeyManagement) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_import_key_requires_authentication (test.on_yubikey.test_piv.KeyManagement) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_read_certificate_does_not_require_authentication (test.on_yubikey.test_piv.KeyManagement) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_authenticate_twice_does_not_throw (test.on_yubikey.test_piv.ManagementKeyReadOnly) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_reset_resets_has_stored_key_flag (test.on_yubikey.test_piv.ManagementKeyReadOnly) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_reset_while_verified_throws_nice_ValueError (test.on_yubikey.test_piv.ManagementKeyReadOnly) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_set_mgm_key_does_not_change_key_if_not_authenticated (test.on_yubikey.test_piv.ManagementKeyReadOnly) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_set_stored_mgm_key_does_not_destroy_key_if_pin_not_verified (test.on_yubikey.test_piv.ManagementKeyReadOnly) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_set_mgm_key_changes_mgm_key (test.on_yubikey.test_piv.ManagementKeyReadWrite) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_set_stored_mgm_key_succeeds_if_pin_is_verified (test.on_yubikey.test_piv.ManagementKeyReadWrite) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_set_stored_random_mgm_key_succeeds_if_pin_is_verified (test.on_yubikey.test_piv.ManagementKeyReadWrite) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_sign_with_pin_policy_always_requires_pin_every_time (test.on_yubikey.test_piv.Operations) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_sign_with_pin_policy_never_does_not_require_pin (test.on_yubikey.test_piv.Operations) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_sign_with_pin_policy_once_requires_pin_once_per_session (test.on_yubikey.test_piv.Operations) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_set_pin_retries_requires_pin_and_mgm_key (test.on_yubikey.test_piv.UnblockPin) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_set_pin_retries_sets_pin_and_puk_tries (test.on_yubikey.test_piv.UnblockPin) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_unblock_pin_requires_no_previous_authentication (test.on_yubikey.test_piv.UnblockPin) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_unblock_pin_resets_pin_and_retries (test.on_yubikey.test_piv.UnblockPin) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_unblock_pin_with_wrong_puk_throws_ValueError (test.on_yubikey.test_piv.UnblockPin) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_oath_add_credential (test.on_yubikey.test_cli_oath.TestOATH) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_oath_add_credential_prompt (test.on_yubikey.test_cli_oath.TestOATH) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_oath_add_credential_with_space (test.on_yubikey.test_cli_oath.TestOATH) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_oath_add_uri_hotp (test.on_yubikey.test_cli_oath.TestOATH) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_oath_add_uri_totp (test.on_yubikey.test_cli_oath.TestOATH) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_oath_add_uri_totp_prompt (test.on_yubikey.test_cli_oath.TestOATH) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_oath_code (test.on_yubikey.test_cli_oath.TestOATH) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_oath_code_query (test.on_yubikey.test_cli_oath.TestOATH) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_oath_delete (test.on_yubikey.test_cli_oath.TestOATH) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_oath_hidden_cred (test.on_yubikey.test_cli_oath.TestOATH) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_oath_hotp_code (test.on_yubikey.test_cli_oath.TestOATH) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_oath_hotp_steam_code (test.on_yubikey.test_cli_oath.TestOATH) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_oath_info (test.on_yubikey.test_cli_oath.TestOATH) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_oath_reset (test.on_yubikey.test_cli_oath.TestOATH) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_openpgp_info (test.on_yubikey.test_cli_openpgp.TestOpenPGP) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_openpgp_reset (test.on_yubikey.test_cli_openpgp.TestOpenPGP) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_calculate_hex (test.on_yubikey.test_cli_otp.TestSlotCalculate) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_calculate_totp (test.on_yubikey.test_cli_otp.TestSlotCalculate) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_access_code_slot_2 (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_delete_slot_2 (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_invalid_public_id (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_update_settings_enter_slot_2 (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_ykman_program_chalresp_slot_2 (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_ykman_program_chalresp_slot_2_force_fails_without_key (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_ykman_program_chalresp_slot_2_generated (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_ykman_program_chalresp_slot_2_generated_fails_if_also_given (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_ykman_program_chalresp_slot_2_prompt (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_ykman_program_hotp_slot_2 (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_ykman_program_hotp_slot_2_prompt (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_ykman_program_otp_slot_2 (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_ykman_program_otp_slot_2_generate_id_conflicts_private_id (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_ykman_program_otp_slot_2_generate_key_conflicts_key (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_ykman_program_otp_slot_2_generated_all (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_ykman_program_otp_slot_2_generated_private_id (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_ykman_program_otp_slot_2_generated_secret_key (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_ykman_program_otp_slot_2_options (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_ykman_program_otp_slot_2_prompt (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_ykman_program_otp_slot_2_serial_id_conflicts_public_id (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_ykman_program_otp_slot_2_serial_public_id (test.on_yubikey.test_cli_otp.TestSlotProgramming) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_de_scancodes (test.on_yubikey.test_cli_otp.TestSlotStaticPassword) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_generate_pw (test.on_yubikey.test_cli_otp.TestSlotStaticPassword) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_generate_pw_no_length (test.on_yubikey.test_cli_otp.TestSlotStaticPassword) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_generate_pw_too_long (test.on_yubikey.test_cli_otp.TestSlotStaticPassword) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_generate_zero_length (test.on_yubikey.test_cli_otp.TestSlotStaticPassword) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_overwrite_prompt (test.on_yubikey.test_cli_otp.TestSlotStaticPassword) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_provide_valid_pw (test.on_yubikey.test_cli_otp.TestSlotStaticPassword) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_provide_valid_pw_prompt (test.on_yubikey.test_cli_otp.TestSlotStaticPassword) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_too_long (test.on_yubikey.test_cli_otp.TestSlotStaticPassword) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_unsupported_chars (test.on_yubikey.test_cli_otp.TestSlotStaticPassword) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_us_scancodes (test.on_yubikey.test_cli_otp.TestSlotStaticPassword) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_ykman_otp_info (test.on_yubikey.test_cli_otp.TestSlotStatus) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_ykman_swap_slots (test.on_yubikey.test_cli_otp.TestSlotStatus) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_de_layout (test.test_scancodes.TestScanMap) ... ok
test_us_layout (test.test_scancodes.TestScanMap) ... ok
test_bytes2int (test.test_util.TestUtilityFunctions) ... ok
test_form_factor_from_code (test.test_util.TestUtilityFunctions) ... ok
test_format_code (test.test_util.TestUtilityFunctions) ... ok
test_generate_static_pw (test.test_util.TestUtilityFunctions) ... ok
test_hmac_shorten_key (test.test_util.TestUtilityFunctions) ... ok
test_is_pkcs12 (test.test_util.TestUtilityFunctions) ... ok
test_modhex_decode (test.test_util.TestUtilityFunctions) ... ok
test_modhex_encode (test.test_util.TestUtilityFunctions) ... ok
test_parse_tlvs (test.test_util.TestUtilityFunctions) ... ok
test_parse_truncated (test.test_util.TestUtilityFunctions) ... ok
test_time_challenge (test.test_util.TestUtilityFunctions) ... ok
test_tlv (test.test_util.TestUtilityFunctions) ... ok
test_generate_random_management_key (test.test_piv.TestPivFunctions) ... ok
test_ykman_version (test.test_external_libs.TestExternalLibraries) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'
test_ykman_version_not_found (test.test_external_libs.TestExternalLibraries) ... skipped 'DESTRUCTIVE_TEST_YUBIKEY_SERIAL == None'

----------------------------------------------------------------------
Ran 126 tests in 0.037s

OK (skipped=98)
```

**Comment by dagheyman** [comment]
Updated the MANIFEST.in file, next release should include the missing files.

**Comment by gktrk** [comment]
Thanks for the quick fix!
