### ISSUE TITLE
fido2 module not found

### ISSUE THREAD

**Issue by kalgecin** [Yubico/yubikey-manager#135]
I'm using ubuntu 18.04 and followed the ppa installation instructions. however, the ykman command does not work, only throws the exception that fido2 module is not found.
```
$ ykman --version
Traceback (most recent call last):
  File "/usr/bin/ykman", line 11, in <module>
    load_entry_point('yubikey-manager==0.7.1', 'console_scripts', 'ykman')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/ykman/cli/__main__.py", line 35, in <module>
    from ..descriptor import (get_descriptors, list_devices, open_device,
  File "/usr/lib/python3/dist-packages/ykman/descriptor.py", line 33, in <module>
    from .driver_fido import open_devices as open_fido
  File "/usr/lib/python3/dist-packages/ykman/driver_fido.py", line 32, in <module>
    from fido2.hid import CtapHidDevice, CTAPHID
ModuleNotFoundError: No module named 'fido2'

$ python --version
Python 2.7.15rc1
$ sudo apt install python-fido2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-fido2 is already the newest version (0.3.0~ppa1~bionic1).
0 upgraded, 0 newly installed, 0 to remove and 46 not upgraded.

```

**Comment by dagheyman** [comment]
Thanks for the report, I'll try to reproduce it.
Could you try `$ sudo apt install python3-fido2` ?

**Comment by kalgecin** [comment]
yup, that worked.... 
```
$ sudo apt install python3-fido2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  python3-setuptools
Suggested packages:
  python-setuptools-doc
The following NEW packages will be installed:
  python3-fido2 python3-setuptools
0 upgraded, 2 newly installed, 0 to remove and 46 not upgraded.
Need to get 331 kB of archives.
After this operation, 1,677 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://ru.archive.ubuntu.com/ubuntu bionic/main amd64 python3-setuptools all 39.0.1-2 [248 kB]
Get:2 http://ppa.launchpad.net/yubico/stable/ubuntu bionic/main amd64 python3-fido2 all 0.3.0~ppa1~bionic1 [83.6 kB]
Fetched 331 kB in 1s (302 kB/s)                                                    
Selecting previously unselected package python3-setuptools.
(Reading database ... 202937 files and directories currently installed.)
Preparing to unpack .../python3-setuptools_39.0.1-2_all.deb ...
Unpacking python3-setuptools (39.0.1-2) ...
Selecting previously unselected package python3-fido2.
Preparing to unpack .../python3-fido2_0.3.0~ppa1~bionic1_all.deb ...
Unpacking python3-fido2 (0.3.0~ppa1~bionic1) ...
Setting up python3-setuptools (39.0.1-2) ...
Setting up python3-fido2 (0.3.0~ppa1~bionic1) ...
$ ykman -h
Usage: ykman [OPTIONS] COMMAND [ARGS]...

  Configure your YubiKey via the command line.

Options:
  -v, --version
  -d, --device SERIAL
  -l, --log-level [DEBUG|INFO|WARNING|ERROR|CRITICAL]
                                  Enable logging at given verbosity level
  --log-file FILE                 Write logs to the given FILE instead of standard error; ignored unless --log-level is also set
  -h, --help                      Show this message and exit.

Commands:
  config   Enable/Disable applications.
  fido     Manage FIDO applications.
  info     Show general information.
  list     List connected YubiKeys.
  mode     Manage connection modes (USB Interfaces).
  oath     Manage OATH application.
  openpgp  Manage OpenPGP application.
  otp      Manage OTP Application.
  piv      Manage PIV application.
```

**Comment by dagheyman** [comment]
For some reason [{Python3:Depends}](https://github.com/Yubico/yubikey-manager/blob/master/debian/control#L48) didn't resolve to the right dependency but to the python2 version instead. I've uploaded a [new version](https://launchpad.net/~yubico/+archive/ubuntu/stable/+build/15106921) that hopefully works around this, but it has not been built by Launchpad yet.

**Comment by LDVSOFT** [comment]
That's fast reaction! I was using `aptitude` and it showed that `python3-fido2` dependancy was changed to `python-fido2`. Hopefully, the new build would arrive soon.

**Comment by dagheyman** [comment]
New versions seems to work well.
