### ISSUE TITLE
ykman.driver_ccid.CCIDError: Failed to transmit with protocol T1. Card was reset. (or unpowered)

### ISSUE THREAD

**Issue by obeleh** [Yubico/yubikey-manager#137]
when I use pip2 or brew:

```
Traceback (most recent call last):
  File "/usr/local/bin/ykman", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/ykman/cli/__main__.py", line 212, in main
    cli(obj={})
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ykman/cli/util.py", line 77, in inner
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ykman/cli/__main__.py", line 154, in cli
    dev = _run_cmd_for_single(ctx, subcmd.name, transports)
  File "/usr/local/lib/python2.7/site-packages/ykman/cli/__main__.py", line 115, in _run_cmd_for_single
    return descriptor.open_device(transports)
  File "/usr/local/lib/python2.7/site-packages/ykman/descriptor.py", line 87, in open_device
    dev = YubiKey(self, drv)
  File "/usr/local/lib/python2.7/site-packages/ykman/device.py", line 228, in __init__
    usb_supported = driver.probe_capabilities()
  File "/usr/local/lib/python2.7/site-packages/ykman/driver_ccid.py", line 161, in probe_capabilities
    self.select(aid)
  File "/usr/local/lib/python2.7/site-packages/ykman/driver_ccid.py", line 189, in select
    return self.send_apdu(0, GP_INS_SELECT, 0x04, 0, aid)
  File "/usr/local/lib/python2.7/site-packages/ykman/driver_ccid.py", line 178, in send_apdu
    raise CCIDError(e)
ykman.driver_ccid.CCIDError: Failed to transmit with protocol T1. Card was reset.
```

When I use pip3:

```
sjuuls-mbp:~ sjuul$ ykman info
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ykman/device.py", line 197, in __init__
    config = DeviceConfig(driver.read_config())
  File "/usr/local/lib/python3.7/site-packages/ykman/driver_ccid.py", line 147, in read_config
    raise NotSupportedError()
ykman.driver.NotSupportedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ykman/driver_ccid.py", line 175, in send_apdu
    resp, sw1, sw2 = self._conn.transmit(header + body)
  File "/usr/local/lib/python3.7/site-packages/smartcard/CardConnectionDecorator.py", line 82, in transmit
    return self.component.transmit(bytes, protocol)
  File "/usr/local/lib/python3.7/site-packages/smartcard/CardConnection.py", line 146, in transmit
    data, sw1, sw2 = self.doTransmit(bytes, protocol)
  File "/usr/local/lib/python3.7/site-packages/smartcard/pcsc/PCSCCardConnection.py", line 205, in doTransmit
    SCardGetErrorMessage(hresult))
smartcard.Exceptions.CardConnectionException: Failed to transmit with protocol T1. Card is unpowered.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ykman", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/ykman/cli/__main__.py", line 212, in main
    cli(obj={})
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/ykman/cli/util.py", line 77, in inner
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/ykman/cli/__main__.py", line 154, in cli
    dev = _run_cmd_for_single(ctx, subcmd.name, transports)
  File "/usr/local/lib/python3.7/site-packages/ykman/cli/__main__.py", line 115, in _run_cmd_for_single
    return descriptor.open_device(transports)
  File "/usr/local/lib/python3.7/site-packages/ykman/descriptor.py", line 87, in open_device
    dev = YubiKey(self, drv)
  File "/usr/local/lib/python3.7/site-packages/ykman/device.py", line 228, in __init__
    usb_supported = driver.probe_capabilities()
  File "/usr/local/lib/python3.7/site-packages/ykman/driver_ccid.py", line 161, in probe_capabilities
    self.select(aid)
  File "/usr/local/lib/python3.7/site-packages/ykman/driver_ccid.py", line 189, in select
    return self.send_apdu(0, GP_INS_SELECT, 0x04, 0, aid)
  File "/usr/local/lib/python3.7/site-packages/ykman/driver_ccid.py", line 178, in send_apdu
    raise CCIDError(e)
ykman.driver_ccid.CCIDError: Failed to transmit with protocol T1. Card is unpowered.
```

**Comment by emlun** [comment]
Hi! A couple of questions:

1. What were you trying to do when this happened?
2. What version of MacOS are you using?
3. What YubiKey model are you using?

**Comment by obeleh** [comment]
1: Trying to install ykman
2: Osx High Sierra `10.13.6 (17G65)`
3: NEO

**Comment by dagheyman** [comment]
Does it help to just re-insert the device? Or does this happen every time?

**Comment by obeleh** [comment]
Just tried again. Same result

**Comment by obeleh** [comment]
I'm open to a debug session in pycharm through something like teamviewer.

**Comment by dagheyman** [comment]
My guess is there is something messing with your CCID connections on macOS. I would start with contacting Yubico Support as @emlun suggested. https://support.yubico.com/support/tickets/new

**Comment by dainnilsson** [comment]
Closing this issue as it relates to ykman 3.x. If this is still a problem with ykman 4.0, please feel free to reopen.

**Comment by scalp42** [comment]
Seems to be the same issue as in https://github.com/Yubico/yubikey-manager/issues/137
