### ISSUE TITLE
macOS: doesn't start - get stack trace instead

### ISSUE THREAD

**Issue by chiefy** [Yubico/yubikey-manager#16]
```
❯ uname -a
Darwin xxx 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
```

```
Return value of PyObject call is NULL: Traceback (most recent call last):

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ykman/descriptor.py", line 116, in open_device
    dev = open_ccid()

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ykman/driver_ccid.py", line 214, in open_device
    conn.connect()

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/smartcard/CardConnectionDecorator.py", line 54, in connect
    self.component.connect(protocol, mode, disposition)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/smartcard/pcsc/PCSCCardConnection.py", line 128, in connect
    SCardGetErrorMessage(hresult))

smartcard.Exceptions.CardConnectionException: Unable to connect with protocol: T0 or T1. Sharing violation.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 21, in wrapped
    return json.dumps(f(*args, **kwargs))

  File "qrc:///py/yubikey.py", line 51, in refresh
    dev = desc.open_device()

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ykman/descriptor.py", line 122, in open_device
    raise FailedOpeningDeviceException(e)

ykman.descriptor.FailedOpeningDeviceException: Unable to connect with protocol: T0 or T1. Sharing violation.
```

**Comment by dagheyman** [comment]
This is on macOS Sierra right?

"Sharing violation" suggest that something else is locking the key.

Also, I see you are using the GUI, do you succeed when using the command line tool?
Try `$ ykman info`.

**Comment by dagheyman** [comment]
Closing due to lack of information. Also, if it relates to the GUI it belongs in https://github.com/Yubico/yubikey-manager-qt .

**Comment by chiefy** [comment]
Sorry, i will re-open this in the qt project, having the same issue in Manjaro/i3wm
