### ISSUE TITLE
improve error message when libykpers is not available

### ISSUE THREAD

**Issue by j0hnsmith** [Yubico/yubikey-manager#176]
Got this in python 3.6.1 and `yubikey-manager==1.0.1`.

```
$ ykman otp
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/ykman", line 11, in <module>
    load_entry_point('yubikey-manager==1.0.1', 'console_scripts', 'ykman')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ykman/cli/__main__.py", line 212, in main
    cli(obj={})
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ykman/cli/util.py", line 77, in inner
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ykman/cli/__main__.py", line 154, in cli
    dev = _run_cmd_for_single(ctx, subcmd.name, transports)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ykman/cli/__main__.py", line 115, in _run_cmd_for_single
    return descriptor.open_device(transports)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ykman/descriptor.py", line 84, in open_device
    for drv in _list_drivers(transports):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ykman/descriptor.py", line 142, in _list_drivers
    for dev in open_otp():
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ykman/driver_otp.py", line 213, in open_devices
    if libversion < (1, 18):
TypeError: '<' not supported between instances of 'NoneType' and 'tuple'
```

**Comment by dagheyman** [comment]
Thanks for the report!
This usually means `libykpers` is not installed on your system.
(Also see https://github.com/Yubico/yubikey-manager-qt/issues/72 , but note thats's the repo for the GUI)

**Comment by mennanov** [comment]
Is there any way to install it on OS X?

**Comment by dagheyman** [comment]
> Is there any way to install it on OS X?

`$ brew install ykman` should pull it in as a dependency.

**Comment by dagheyman** [comment]
@mennanov I saw [this issue](https://github.com/Yubico/yubikey-manager-qt/issues/121) , they probably have the same root cause. Something seems to be blocking  the OTP transport on your system is my guess. Do you have any software installed that could affect the keyboard access, similar to problems in [this thread](https://github.com/Yubico/yubikey-personalization/issues/34)?

For troubleshooting, could you try:
`$ ykman --log-level DEBUG otp info`
and also
`$ sudo ykman --log-level DEBUG otp info`

**Comment by mennanov** [comment]
> Do you have any software installed that could affect the keyboard access, similar to problems in this thread?

No, i did not install anything keyboard related. However, i did configure GPG. Please, take a look at the updated comment on the issue https://github.com/Yubico/yubikey-manager-qt/issues/121

I've tried the commands you suggested:
```
> sudo ykman --log-level DEBUG otp info
2018-11-27T23:40:07-0800 INFO [ykman.logging_setup.setup:59] Initialized logging for ykman version: 1.0.1
2018-11-27T23:40:07-0800 DEBUG [ykman.descriptor.Descriptor.open_device:75] transports: 0x1, self.mode.transports: 0x7
2018-11-27T23:40:07-0800 DEBUG [ykman.descriptor.open_device:80] Opening driver for serial: None, type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2018-11-27T23:40:07-0800 DEBUG [ykman.descriptor.open_device:82] Attempt 1 of 10
Traceback (most recent call last):
  File "/usr/local/bin/ykman", line 11, in <module>
    load_entry_point('yubikey-manager==1.0.1', 'console_scripts', 'ykman')()
  File "/usr/local/Cellar/ykman/1.0.1/libexec/lib/python3.7/site-packages/ykman/cli/__main__.py", line 212, in main
    cli(obj={})
  File "/usr/local/Cellar/ykman/1.0.1/libexec/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/ykman/1.0.1/libexec/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/ykman/1.0.1/libexec/lib/python3.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/Cellar/ykman/1.0.1/libexec/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/ykman/1.0.1/libexec/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/ykman/1.0.1/libexec/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/ykman/1.0.1/libexec/lib/python3.7/site-packages/ykman/cli/util.py", line 77, in inner
    f(*args, **kwargs)
  File "/usr/local/Cellar/ykman/1.0.1/libexec/lib/python3.7/site-packages/ykman/cli/__main__.py", line 154, in cli
    dev = _run_cmd_for_single(ctx, subcmd.name, transports)
  File "/usr/local/Cellar/ykman/1.0.1/libexec/lib/python3.7/site-packages/ykman/cli/__main__.py", line 115, in _run_cmd_for_single
    return descriptor.open_device(transports)
  File "/usr/local/Cellar/ykman/1.0.1/libexec/lib/python3.7/site-packages/ykman/descriptor.py", line 84, in open_device
    for drv in _list_drivers(transports):
  File "/usr/local/Cellar/ykman/1.0.1/libexec/lib/python3.7/site-packages/ykman/descriptor.py", line 142, in _list_drivers
    for dev in open_otp():
  File "/usr/local/Cellar/ykman/1.0.1/libexec/lib/python3.7/site-packages/ykman/driver_otp.py", line 213, in open_devices
    if libversion < (1, 18):
TypeError: '<' not supported between instances of 'NoneType' and 'tuple'
```

**Comment by dagheyman** [comment]
Thanks, what about `$ ykman --version`, (to see if libykpers is picked up at all), same error?
And does `$ brew info ykpers` mark it as installed?

**Comment by mennanov** [comment]
```
> ykman --version
YubiKey Manager (ykman) version: 1.0.1
Libraries:
    libykpers not found!
    libusb 1.0.22
```

```
> brew info ykpers
ykpers: stable 1.19.0 (bottled)
YubiKey personalization library and tool
https://developers.yubico.com/yubikey-personalization/
/usr/local/Cellar/ykpers/1.19.0_1 (23 files, 461.8KB)
  Poured from bottle on 2018-11-27 at 19:19:14
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ykpers.rb
==> Dependencies
Build: pkg-config ✘
Required: json-c ✔, libyubikey ✔
==> Analytics
install: 621 (30 days), 2,044 (90 days), 9,910 (365 days)
install_on_request: 278 (30 days), 1,000 (90 days), 5,666 (365 days)
build_error: 0 (30 days)
```

**Comment by dagheyman** [comment]
I guess that means it's installed? Does `$ brew reinstall ykpers` change anything?

I just tried on a fresh macOS mojave install and ` $ brew install ykman` installs ykpers as it should it seems.

**Comment by mennanov** [comment]
It helped to solve the problem in subject:

```
> brew reinstall ykpers
==> Reinstalling ykpers 
==> Downloading https://homebrew.bintray.com/bottles/ykpers-1.19.0_1.mojave.bottle.tar.gz
Already downloaded: /Users/renat/Library/Caches/Homebrew/downloads/f83cac89a473c69d4c6a33b494126c17ed2a1189e078e8b7640fda8fde6947a9--ykpers-1.19.0_1.mojave.bottle.tar.gz
==> Pouring ykpers-1.19.0_1.mojave.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink lib/libykpers-1.1.dylib
Target /usr/local/lib/libykpers-1.1.dylib
already exists. You may want to remove it:
  rm '/usr/local/lib/libykpers-1.1.dylib'

To force the link and overwrite all conflicting files:
  brew link --overwrite ykpers

To list all files that would be deleted:
  brew link --overwrite --dry-run ykpers

Possible conflicting files are:
/usr/local/lib/libykpers-1.1.dylib
==> Summary
🍺  /usr/local/Cellar/ykpers/1.19.0_1: 23 files, 461.8KB

> brew link --overwrite ykpers
Linking /usr/local/Cellar/ykpers/1.19.0_1... 11 symlinks created

> brew info ykpers            
ykpers: stable 1.19.0 (bottled)
YubiKey personalization library and tool
https://developers.yubico.com/yubikey-personalization/
/usr/local/Cellar/ykpers/1.19.0_1 (23 files, 461.8KB) *
  Poured from bottle on 2018-11-28 at 00:10:27
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ykpers.rb
==> Dependencies
Build: pkg-config ✘
Required: json-c ✔, libyubikey ✔
==> Analytics
install: 621 (30 days), 2,044 (90 days), 9,910 (365 days)
install_on_request: 278 (30 days), 1,000 (90 days), 5,666 (365 days)
build_error: 0 (30 days)

> ykman --version             
YubiKey Manager (ykman) version: 1.0.1
Libraries:
    libykpers 1.19.0
    libusb 1.0.22
```

However there is still a problem (probably unrelated to this issue):

```
> ykman --log-level DEBUG otp info            
2018-11-28T00:15:06-0800 INFO [ykman.logging_setup.setup:59] Initialized logging for ykman version: 1.0.1
2018-11-28T00:15:06-0800 DEBUG [ykman.descriptor.Descriptor.open_device:75] transports: 0x1, self.mode.transports: 0x7
2018-11-28T00:15:06-0800 DEBUG [ykman.descriptor.open_device:80] Opening driver for serial: None, type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2018-11-28T00:15:06-0800 DEBUG [ykman.descriptor.open_device:82] Attempt 1 of 10
2018-11-28T00:15:06-0800 DEBUG [ykman.driver_otp.open_devices:219] Failed to open key at position 0
2018-11-28T00:15:06-0800 DEBUG [ykman.descriptor.open_device:101] Sleeping for 0.100000 s
2018-11-28T00:15:06-0800 DEBUG [ykman.descriptor.open_device:82] Attempt 2 of 10
2018-11-28T00:15:06-0800 DEBUG [ykman.driver_otp.open_devices:219] Failed to open key at position 0
2018-11-28T00:15:06-0800 DEBUG [ykman.descriptor.open_device:101] Sleeping for 0.200000 s
2018-11-28T00:15:06-0800 DEBUG [ykman.descriptor.open_device:82] Attempt 3 of 10
2018-11-28T00:15:06-0800 DEBUG [ykman.driver_otp.open_devices:219] Failed to open key at position 0
2018-11-28T00:15:06-0800 DEBUG [ykman.descriptor.open_device:101] Sleeping for 0.300000 s
2018-11-28T00:15:06-0800 DEBUG [ykman.descriptor.open_device:82] Attempt 4 of 10
2018-11-28T00:15:06-0800 DEBUG [ykman.driver_otp.open_devices:219] Failed to open key at position 0
2018-11-28T00:15:06-0800 DEBUG [ykman.descriptor.open_device:101] Sleeping for 0.400000 s
2018-11-28T00:15:07-0800 DEBUG [ykman.descriptor.open_device:82] Attempt 5 of 10
2018-11-28T00:15:07-0800 DEBUG [ykman.driver_otp.open_devices:219] Failed to open key at position 0
2018-11-28T00:15:07-0800 DEBUG [ykman.descriptor.open_device:101] Sleeping for 0.500000 s
2018-11-28T00:15:07-0800 DEBUG [ykman.descriptor.open_device:82] Attempt 6 of 10
2018-11-28T00:15:07-0800 DEBUG [ykman.driver_otp.open_devices:219] Failed to open key at position 0
2018-11-28T00:15:07-0800 DEBUG [ykman.descriptor.open_device:101] Sleeping for 0.600000 s
2018-11-28T00:15:08-0800 DEBUG [ykman.descriptor.open_device:82] Attempt 7 of 10
2018-11-28T00:15:08-0800 DEBUG [ykman.driver_otp.open_devices:219] Failed to open key at position 0
2018-11-28T00:15:08-0800 DEBUG [ykman.descriptor.open_device:101] Sleeping for 0.700000 s
2018-11-28T00:15:09-0800 DEBUG [ykman.descriptor.open_device:82] Attempt 8 of 10
2018-11-28T00:15:09-0800 DEBUG [ykman.driver_otp.open_devices:219] Failed to open key at position 0
2018-11-28T00:15:09-0800 DEBUG [ykman.descriptor.open_device:101] Sleeping for 0.800000 s
2018-11-28T00:15:10-0800 DEBUG [ykman.descriptor.open_device:82] Attempt 9 of 10
2018-11-28T00:15:10-0800 DEBUG [ykman.driver_otp.open_devices:219] Failed to open key at position 0
2018-11-28T00:15:10-0800 DEBUG [ykman.descriptor.open_device:101] Sleeping for 0.900000 s
2018-11-28T00:15:10-0800 DEBUG [ykman.descriptor.open_device:82] Attempt 10 of 10
2018-11-28T00:15:10-0800 DEBUG [ykman.driver_otp.open_devices:219] Failed to open key at position 0
2018-11-28T00:15:10-0800 DEBUG [ykman.descriptor.open_device:101] Sleeping for 1.000000 s
2018-11-28T00:15:11-0800 DEBUG [ykman.descriptor.open_device:103] No matching device found
Usage: ykman [OPTIONS] COMMAND [ARGS]...

Error: Failed connecting to the YubiKey.
```

It worked with `sudo` though:

```
> sudo ykman --log-level DEBUG otp info
Enter PIN for 'Certificate For PIV Authentication (Yubico PIV Authentication)': 
2018-11-28T00:15:33-0800 INFO [ykman.logging_setup.setup:59] Initialized logging for ykman version: 1.0.1
2018-11-28T00:15:33-0800 DEBUG [ykman.descriptor.Descriptor.open_device:75] transports: 0x1, self.mode.transports: 0x7
2018-11-28T00:15:33-0800 DEBUG [ykman.descriptor.open_device:80] Opening driver for serial: None, type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2018-11-28T00:15:33-0800 DEBUG [ykman.descriptor.open_device:82] Attempt 1 of 10
2018-11-28T00:15:33-0800 DEBUG [ykman.driver_otp.open_devices:221] Success in opening key at position 0
2018-11-28T00:15:33-0800 DEBUG [ykman.descriptor.open_device:86] Found driver: <ykman.driver_otp.OTPDriver object at 0x111198780>, key_type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2018-11-28T00:15:33-0800 DEBUG [ykman.device.__init__:198] Read config from device...
2018-11-28T00:15:33-0800 DEBUG [ykman.device.__init__:200] Success!
2018-11-28T00:15:33-0800 DEBUG [ykman.device.__init__:284] Identified YubiKey 5
Slot 1: programmed
Slot 2: programmed
2018-11-28T00:15:33-0800 DEBUG [ykman.driver_otp.close:203] Close <ykman.driver_otp.OTPDriver object at 0x111198780>
2018-11-28T00:15:33-0800 DEBUG [ykman.driver_otp.__del__:208] Destroy <ykman.driver_otp.OTPDriver object at 0x111198780>
```

Please, notice that this security key is configured as a smart card. Could this be an issue?
