### ISSUE TITLE
ykman raises on raw data objects instead of certs

### ISSUE THREAD

**Issue by smrt28** [Yubico/yubikey-manager#198]
Hi,

If you write raw data to the slot instead of a valid certificate like this:

```
head -1000 /dev/urandom | yubico-piv-tool -a write-object --id 0x5FC10C
```
ykman raises an exception even if other slots contain valid certificates. Observed on Yubikey 4 and 5.

```
$ ykman piv info
PIV version: 5.1.2
PIN tries remaining: 3
CHUID:	No data available.
CCC: 	No data available.
Traceback (most recent call last):
  File "/usr/bin/ykman", line 11, in <module>
    load_entry_point('yubikey-manager==1.0.1', 'console_scripts', 'ykman')()
  File "/usr/lib/python3/dist-packages/ykman/cli/__main__.py", line 212, in main
    cli(obj={})
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3/dist-packages/ykman/cli/piv.py", line 151, in info
    for (slot, cert) in controller.list_certificates().items():
  File "/usr/lib/python3/dist-packages/ykman/piv.py", line 843, in list_certificates
    certs[slot] = self.read_certificate(slot)
  File "/usr/lib/python3/dist-packages/ykman/piv.py", line 804, in read_certificate
    return x509.load_der_x509_certificate(data[TAG.CERTIFICATE],
KeyError: <TAG.CERTIFICATE: 112>
```

**Comment by dagheyman** [comment]
Thanks. Agreed that it should not crash like this in this scenario, will look into it.

**Comment by dagheyman** [comment]
This should not be the case anymore, closing.
