### ISSUE TITLE
Change PIN to less than 6 characters error

### ISSUE THREAD

**Issue by v1nc** [Yubico/yubikey-manager#210]
- YubiKey Manager (ykman) version: 2.0.0
- How was it installed?: pacman
- Operating system and version: 4.18.9-arch1-1-ARCH
- YubiKey model and version: YubiKey 5 NFC Firmware version: 5.1.2
- Bug description summary:
Trying to change the PIN to less than 6 characters should throw an error like "less than 6 characters is not allowed". Instead, an APDUError is raised. 
---

Steps to reproduce
---

- `ykman piv change-pin `
- change pin to something less than 6 characters.

Expected result
---
Print `less than 6 characters is not allowed`

Actual results and logs
---

> Traceback (most recent call last):
  File "/usr/bin/ykman", line 11, in <module>
    load_entry_point('yubikey-manager==2.0.0', 'console_scripts', 'ykman')()
  File "/usr/lib/python3.7/site-packages/ykman/cli/__main__.py", line 246, in main
    cli(obj={})
  File "/usr/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/ykman/cli/piv.py", line 637, in change_pin
    controller.change_pin(pin, new_pin)
  File "/usr/lib/python3.7/site-packages/ykman/piv.py", line 600, in change_pin
    _pack_pin(old_pin) + _pack_pin(new_pin))
  File "/usr/lib/python3.7/site-packages/ykman/piv.py", line 557, in send_cmd
    raise APDUError(resp, sw)
ykman.driver_ccid.APDUError: APDU error: SW=0x6a80

**Comment by dagheyman** [comment]
Thanks for the report! We'll look into this.
