### ISSUE TITLE
Error when resolving YkmanContextObject

### ISSUE THREAD

**Issue by rgerganov** [Yubico/yubikey-manager#214]
- YubiKey Manager (ykman) version:
top-of-tree
- How was it installed?:
`pip install -e .`
- Operating system and version:
Ubuntu 14.04
- YubiKey model and version:
Yubikey 5 NFC
- Bug description summary:
Error is thrown when running `ykman fido info`

Steps to reproduce
---

`ykman fido info`

Expected result
---

information about FIDO functions

Actual results and logs
---
```
Traceback (most recent call last):
  File "venv/bin/ykman", line 11, in <module>
    load_entry_point('yubikey-manager', 'console_scripts', 'ykman')()
  File "/opt/src/yubikey-manager/ykman/cli/__main__.py", line 246, in main
    cli(obj={})
  File "/opt/src/yubikey-manager/venv/lib/python3.4/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/src/yubikey-manager/venv/lib/python3.4/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/src/yubikey-manager/venv/lib/python3.4/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/src/yubikey-manager/venv/lib/python3.4/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/src/yubikey-manager/venv/lib/python3.4/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/src/yubikey-manager/venv/lib/python3.4/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/src/yubikey-manager/venv/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/src/yubikey-manager/ykman/cli/fido.py", line 87, in info
    controller = ctx.obj['controller']
  File "/opt/src/yubikey-manager/ykman/cli/util.py", line 89, in __getitem__
    self.resolve()
  File "/opt/src/yubikey-manager/ykman/cli/util.py", line 86, in resolve
    self._objects[k] = f()
TypeError: 'Fido2Controller' object is not callable
```

Other info
---

Will submit a PR

**Comment by dagheyman** [comment]
Does this happen every time? Only on Python 3.4? Only the fido command?

**Comment by rgerganov** [comment]
Yes, it happens every time with Python 3.4 when running `ykman fido info`. Other commands seems to run fine but I haven't tested them all.
