### ISSUE TITLE
ykman.driver_otp.YkpersError: ykpers error 2, b'wrong size'

### ISSUE THREAD

**Issue by xamox** [Yubico/yubikey-manager#224]
- YubiKey Manager (ykman) version:
YubiKey Manager (ykman) version: 2.0.0
Libraries:
    libykpers 1.19.2
    libusb 1.0.21

- How was it installed?:
Official PPA via Ubuntu apt-get.

- Operating system and version:
Ubuntu 18.04

- YubiKey model and version:
Nano 4
4.3.7

- Bug description summary:
` ykman otp chalresp -g 2                                                                                                                                            835ms  Thu 21 Feb 2019 03:07:30 PM EST
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ykman/driver_otp.py", line 143, in read_config
    self._dev, 0, 0, resp, byref(buf_size)))
  File "/usr/lib/python3/dist-packages/ykman/driver_otp.py", line 71, in check
    raise YkpersError(ykpers.yk_get_errno())
ykman.driver_otp.YkpersError: ykpers error 2, b'wrong size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ykman", line 11, in <module>
    load_entry_point('yubikey-manager==2.0.0', 'console_scripts', 'ykman')()
  File "/usr/lib/python3/dist-packages/ykman/cli/__main__.py", line 246, in main
    cli(obj={})
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3/dist-packages/ykman/cli/otp.py", line 396, in chalresp
    controller = ctx.obj['controller']
  File "/usr/lib/python3/dist-packages/ykman/cli/util.py", line 88, in __getitem__
    self.resolve()
  File "/usr/lib/python3/dist-packages/ykman/cli/util.py", line 85, in resolve
    self._objects[k] = f()
  File "/usr/lib/python3/dist-packages/ykman/cli/__main__.py", line 188, in resolve_device
    dev = _run_cmd_for_single(ctx, subcmd.name, transports, reader)
  File "/usr/lib/python3/dist-packages/ykman/cli/__main__.py", line 128, in _run_cmd_for_single
    return descriptor.open_device(transports)
  File "/usr/lib/python3/dist-packages/ykman/descriptor.py", line 87, in open_device
    dev = YubiKey(self, drv)
  File "/usr/lib/python3/dist-packages/ykman/device.py", line 199, in __init__
    config = DeviceConfig(driver.read_config())
  File "/usr/lib/python3/dist-packages/ykman/driver_otp.py", line 152, in read_config
    self._dev, 0, 0, resp, byref(buf_size)))
  File "/usr/lib/python3/dist-packages/ykman/driver_otp.py", line 71, in check
    raise YkpersError(ykpers.yk_get_errno())
ykman.driver_otp.YkpersError: ykpers error 2, b'wrong size'
`

Steps to reproduce
---

[Please explain what you did when the bug appeared, and if and how you have been
able to reproduce it.]

I tried to open yubikey manager, I believe it crashed, after that yubikey would not function stating serial-api-visible disabled.   Could not get it working, so deleted configuration on yubikey, apt-get remove --purge and uninstalled all yubikey libs, then apt-get re-installed all the libs and now it's throwing this error.

Expected result
---

[What did you expect to happen when you did the above?]
Configure the 2nd slot with challenge response

Actual results and logs
---

[What actually happened?]

Other info
---

[Anything else you would like to add?]
Not sure how it got into this state.  I had sudo setup to use yubikey PAM, had to live boot and remove it because system was stuck,  now yubikey seems to be in unrecoverable state.  Not sure how this has happened as I've been using the key fine for probably 10 months.

**Comment by dagheyman** [comment]
Thanks, I can reproduce this. It even seems to happen with `$ ykman otp info` if latest libykpers is installed.

**Comment by dagheyman** [comment]
Libykpers 1.19.3 is out. `$sudo apt update && sudo apt upgrade` should resolve the issue!

**Comment by xamox** [comment]
That worked, great thanks for the quick turn around!
