### ISSUE TITLE
Specify what version of cryptography is needed

### ISSUE THREAD

**Issue by opoplawski** [Yubico/yubikey-manager#230]
- YubiKey Manager (ykman) version: 2.1.0
- How was it installed?: Source
- Operating system and version: Scientific Linux 7.5
- Bug description summary:

It appears that ykman uses the rfc4514_string() function from cryptography in version 2.5.   It would be helpful if the required version was specified in setup.py.

Also, with version 2.5 and cffi 1.9.1 I'm getting the following warning with write-object:
```
/usr/lib64/python3.6/site-packages/cryptography/hazmat/backends/openssl/ciphers.py:114: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  operation
/usr/lib64/python3.6/site-packages/cryptography/hazmat/backends/openssl/ciphers.py:140: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  self._backend._ffi.from_buffer(data), len(data)
```

**Comment by dagheyman** [comment]
This is a good point, we'll look into it.

In practice the lowest version we currently require is the one available in Ubuntu Xenial, [which is 1.2.3](https://packages.ubuntu.com/xenial/python-cryptography). The use of `rfc4514_string()` has fallback logic if it's not available.

**Comment by opoplawski** [comment]
Ah, I see - but the fallback is generating a traceback for me as well:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ykman/cli/piv.py", line 162, in info
    subject_dn = cert.subject.rfc4514_string()
AttributeError: 'Name' object has no attribute 'rfc4514_string'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ykman", line 11, in <module>
    load_entry_point('yubikey-manager==2.1.0', 'console_scripts', 'ykman')()
  File "/usr/lib/python3.6/site-packages/ykman/cli/__main__.py", line 253, in main
    cli(obj={})
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/ykman/cli/piv.py", line 168, in info
    subject_cn = subject_cn[0].value if len(cn) > 0 else 'None'
NameError: name 'cn' is not defined
```

**Comment by dagheyman** [comment]
Thanks, that is indeed a bug. Expect a fix in the next version.

**Comment by hadmut** [comment]
Hi,

any estimate about when this bug fix will make its way into the ubuntu ppa?
