### ISSUE TITLE
"Crash" when no Yubikey is present: FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/hidraw'

### ISSUE THREAD

**Issue by LudovicRousseau** [Yubico/yubikey-manager#233]
- YubiKey Manager (ykman) version: 2.1.0
- How was it installed?: Debian unstable package
- Operating system and version: Debian testing/unstable
- YubiKey model and version: not important
- Bug description summary:
If I run `ykman list` with no yubikey inserted I get an exception.
```
$ ykman list
Traceback (most recent call last):
  File "/usr/bin/ykman", line 11, in <module>
    load_entry_point('yubikey-manager==2.1.0', 'console_scripts', 'ykman')()
  File "/usr/lib/python3/dist-packages/ykman/cli/__main__.py", line 253, in main
    cli(obj={})
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3/dist-packages/ykman/cli/__main__.py", line 213, in list_keys
    for dev in list_devices():
  File "/usr/lib/python3/dist-packages/ykman/descriptor.py", line 152, in list_devices
    for d in _list_drivers(transports):
  File "/usr/lib/python3/dist-packages/ykman/descriptor.py", line 146, in _list_drivers
    for dev in open_fido():
  File "/usr/lib/python3/dist-packages/ykman/driver_fido.py", line 97, in open_devices
    for dev in CtapHidDevice.list_devices(descriptor_filter):
  File "/usr/lib/python3/dist-packages/fido2/hid.py", line 136, in list_devices
    for d in hidtransport.hid.Enumerate():
  File "/usr/lib/python3/dist-packages/fido2/_pyu2f/linux.py", line 183, in Enumerate
    for hidraw in os.listdir('/sys/class/hidraw'):
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/hidraw'
```

Steps to reproduce
---

Run `ykman list` with no yubikey inserted.

Expected result
---

A "nice" error message like 'no key found"

Actual results and logs
---

Python backtrace of an exception.
See above.

Other info
---

I use a Dell E5570 laptop. The keyboard and trackpad are not on the USB bus.
I have:
```
$ lsusb 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 8087:0a2b Intel Corp. 
Bus 001 Device 004: ID 1bcf:28b8 Sunplus Innovation Technology Inc. 
Bus 001 Device 003: ID 0a5c:5834 Broadcom Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Once I inserted and removed the yubikey the directory `/sys/class/hidraw` exist and is empty. `ykman list` does not report anything but does not "crash".

**Comment by dagheyman** [comment]
Thanks for the report! I'll make sure this error is handled better in future versions.

**Comment by jmyreen** [comment]
I ran into this bug, too. It happens when no HID device has yet been plugged in, and HID support has been compiled as a kernel module. The module is loaded on demand, and once loaded, it provides the `/sys/class/hidraw` directory.

**Comment by dainnilsson** [comment]
This should now be fixed.
