### ISSUE TITLE
Touch validation OATH/TOTP keep the yubikey blinking

### ISSUE THREAD

**Issue by bobsaintcool** [Yubico/yubikey-manager#264]
- YubiKey Manager (ykman) version:

```
$ ykman --version 
YubiKey Manager (ykman) version: 3.0.0
Libraries:
    libykpers 1.19.3
    libusb 1.0.22
```

- How was it installed?: Package manager either pacman or apt

- Operating system and version:

```
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```

But also Debian/Sid.

- YubiKey model and version:

```
$ ykman info

Device type: YubiKey 5 NFC
Serial number: X
Firmware version: 5.1.2
Form factor: Keychain (USB-A)
Enabled USB interfaces: CCID
NFC interface is disabled.
Configured applications are protected by a lock code.

Applications    USB             NFC
OTP             Disabled        Disabled
FIDO U2F        Disabled        Disabled
OpenPGP         Disabled        Disabled
PIV             Disabled        Disabled
OATH            Enabled         Disabled
FIDO2           Disabled        Disabled
```

- Bug description summary:

I would like to have my Yubikey only work in OATH/TOTP using the USB mode and having both a password and touch validation to get my code. After configuring like described below and asking to retrieve some code I can enter my password, the key button begins to blink slowly to ask for user touch. When I touch it, the key begin to blink very fast and the code is never released.

Steps to reproduce
---

```
$ ykman --device X config set-lock-code
$ ykman config nfc -D
$ for mode in U2F OTP FIDO2 PIV OPGP; do
for> ykman --device X config usb -d "${mode}"
for> done
$ ykman --device X config usb --touch-eject --autoeject-timeout 30 --chalresp-timeout 15 -e OATH
```
[unplug and plug]
```
$ ykman --device X oath set-password
$ ykman --device X oath remember-password -F
$ ykman --device X oath remember-password -c
$ ykman --device X oath uri -t 'otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example'
```

```
$ ykman --device X oath code alice@google.com
Enter your password:
Touch your YubiKey...
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ykman/driver_ccid.py", line 229, in send_apdu
    resp, sw1, sw2 = self._conn.transmit(header + body)
  File "/usr/lib/python3.7/site-packages/smartcard/CardConnectionDecorator.py", line 82, in transmit
    return self.component.transmit(bytes, protocol)
  File "/usr/lib/python3.7/site-packages/smartcard/CardConnection.py", line 146, in transmit
    data, sw1, sw2 = self.doTransmit(bytes, protocol)
  File "/usr/lib/python3.7/site-packages/smartcard/pcsc/PCSCCardConnection.py", line 205, in doTransmit
    SCardGetErrorMessage(hresult))
smartcard.Exceptions.CardConnectionException: Failed to transmit with protocol T1. Transaction failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ykman", line 11, in <module>
    load_entry_point('yubikey-manager==3.0.0', 'console_scripts', 'ykman')()
  File "/usr/lib/python3.7/site-packages/ykman/cli/__main__.py", line 260, in main
    cli(obj={})
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/ykman/cli/oath.py", line 367, in code
    creds = [(cred, controller.calculate(cred))]
  File "/usr/lib/python3.7/site-packages/ykman/oath.py", line 324, in calculate
    resp = self.send_apdu(INS.CALCULATE, 0, 0, data)
  File "/usr/lib/python3.7/site-packages/ykman/oath.py", line 252, in send_apdu
    resp, sw = self._driver.send_apdu(0, ins, p1, p2, data, check=None)
  File "/usr/lib/python3.7/site-packages/ykman/driver_ccid.py", line 232, in send_apdu
    raise CCIDError(e)
ykman.driver_ccid.CCIDError: Failed to transmit with protocol T1. Transaction failed.
```

Expected result
---

i'm expecting my TOTP code released and not the key bliking fast

Actual results and logs
---

```
$  ykman --log-level debug --device X oath code alice@google.com
2019-07-01T21:58:16+0000 INFO [ykman.logging_setup.setup:59] Initialized logging for ykman version: 3.0.0
2019-07-01T21:58:16+0000 DEBUG [ykman.descriptor._open_driver:168] Opening driver for transports: TRANSPORT.CCID, serial: 9072403, key_type: None, mode: None
2019-07-01T21:58:16+0000 DEBUG [ykman.descriptor._open_driver:170] Attempt 1 of 10
2019-07-01T21:58:16+0000 DEBUG [ykman.device.__init__:198] Read config from device...
2019-07-01T21:58:16+0000 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00a4040008a000000527471117'
2019-07-01T21:58:16+0000 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'5669727475616c206d6772202d2046572076657273696f6e20352e312e329000'
2019-07-01T21:58:16+0000 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'001d000000'
2019-07-01T21:58:16+0000 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'2b0102023f030200240204008a6f1304010105030501020602001e07010f0801800d02023f0e0200000a01019000'
2019-07-01T21:58:16+0000 DEBUG [ykman.device.__init__:200] Success!
2019-07-01T21:58:16+0000 DEBUG [ykman.device.__init__:292] Identified YubiKey 5
2019-07-01T21:58:16+0000 DEBUG [ykman.descriptor._open_driver:175] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x6123519cf908> serial: 9072403, key_type: YUBIKEY.YK4, mode: CCID
2019-07-01T21:58:16+0000 DEBUG [ykman.device.__init__:198] Read config from device...
2019-07-01T21:58:16+0000 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00a4040008a000000527471117'
2019-07-01T21:58:16+0000 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'5669727475616c206d6772202d2046572076657273696f6e20352e312e329000'
2019-07-01T21:58:16+0000 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'001d000000'
2019-07-01T21:58:16+0000 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'2b0102023f030200240204008a6f1304010105030501020602001e07010f0801800d02023f0e0200000a01019000'
2019-07-01T21:58:16+0000 DEBUG [ykman.device.__init__:200] Success!
2019-07-01T21:58:16+0000 DEBUG [ykman.device.__init__:292] Identified YubiKey 5
2019-07-01T21:58:16+0000 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00a4040007a0000005272101'
2019-07-01T21:58:16+0000 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'790305010271083264335f5c98ce917408cdfa00b96d9fa7877b01019000'
Enter your password:
*2019-07-01T21:58:24+0000 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00a30000207514872739b2c05da317d5d8eca458b2d965e14eae9874085b5757e3bf9629d0'
2019-07-01T21:58:24+0000 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'7514e69877c2bb2210563a489487ae25609df1b344249000'
2019-07-01T21:58:24+0000 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00a400010a740800000000031a7bcc'
2019-07-01T21:58:24+0000 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'71184578616d706c653a616c69636540676f6f676c652e636f6d7c01069000'
Touch your YubiKey...
2019-07-01T21:58:24+0000 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00a200002471184578616d706c653a616c69636540676f6f676c652e636f6d740800000000031a7bcc'
[...]
2019-07-01T22:00:27+0000 DEBUG [ykman.driver_ccid.close:269] Close <ykman.driver_ccid.CCIDDriver object at 0x6123519cf908>
Aborted!
2019-07-01T22:00:27+0000 DEBUG [ykman.driver_ccid.__del__:273] Destroy <ykman.driver_ccid.CCIDDriver object at 0x6123519cf908>
2019-07-01T22:00:27+0000 DEBUG [ykman.driver_ccid.close:269] Close <ykman.driver_ccid.CCIDDriver object at 0x6123519cf908>
```

Other info
---

Not sure its a bug or a bad configuration, but I've been able to perform this kind of setup with some Yubikey 5 before.

**Comment by emlun** [comment]
Thanks for the report! We've reproduced the behaviour and are working to diagnose the root cause, but it seems related to the `--touch-eject` option of `config usb`.

As a workaround in the meantime, you can either disable `--touch-eject`, or by enabling one of the apps `OTP`, `U2F` or `FIDO2`. That enables the OTP or FIDO interface, and the `--touch-eject` setting takes effect only if CCID is the only active interface.

**Comment by bobsaintcool** [comment]
Mentioned workaround works thanks. Give me an head up if you manage to get the root cause!

**Comment by emlun** [comment]
We've confirmed that this is a firmware bug. The firmware team has fixed it, but it will be some time before the fix is released to manufacturing and there's not much we can do for existing YubiKeys except for the above workaround. Thanks again for the report!

**Comment by Haris-AK** [comment]
Did this occur with any other versions as I seem to have the same bug on v5.7.4
