### ISSUE TITLE
CCID only mode: Access codes prevent mode change

### ISSUE THREAD

**Issue by FeatheredSerpent** [Yubico/yubikey-manager#273]
- YubiKey Manager (ykman) version: 3.0.0
- Yubikey Personalization (ykpersonalize.exe) version: 1.20.0
- How was it installed?: yubikey-manager-qt-1.1.2-win64.exe / ykpers-1.20.0-win64.zip
- Operating system and version: Microsoft Windows 10 Enterprise 1903 x64 (10.0.18362)
- YubiKey model and version: YubiKey 4 Nano (Firmware 4.3.4)
- Bug description summary:

It seems as if I'm locked out of my YubiKey after enabling CCID only mode using _ykpersonalize.exe -m 81:3:3_.

I can't enable OTP/FIDO mode because slot 1/2 have an access code set.
But in order to remove the access code OTP mode has to be enabled...?

Is there any way to fix the problem? 

@aidantwoods in #12 seems to have had [the same](https://github.com/Yubico/yubikey-manager/issues/12#issuecomment-309254395) problem before.

PS: I've filed a support ticket.

**ykpersonalize.exe -m 81:3:3**
```
Firmware version 4.3.4 Touch level 768 Unconfigured

Serial number : XXXXXXX



The USB mode will be set to: 0x81

The challenge response timeout will be set to: 3

The smartcard autoeject timeout will be set to: 3



Commit? (y/n) [n]: y

Attempting to write configuration to the yubikey...WARNING: Changing mode will require you to use another tool (ykneomgr or u2f-host) to switch ba

ck if OTP mode is disabled, really commit? (y/n) [n]: y

 success
```

**ykman.exe info**
```
Device type: YubiKey 4

Serial number: XXXXXXX
Firmware version: 4.3.4

Enabled USB interfaces: CCID



Applications

OTP Disabled

FIDO U2F Disabled

OpenPGP Enabled

PIV Enabled

OATH Enabled

FIDO2 Not available
```

**ykman.exe -lDEBUG mode OTP+FIDO+CCID -f**
```
2019-07-31T07:30:41+0200 INFO [ykman.logging_setup.setup:59] Initialized logging for ykman version: 3.0.0

2019-07-31T07:30:41+0200 DEBUG [ykman.descriptor.Descriptor.open_device:84] transports: 0x7, self.mode.transports: 0x4

2019-07-31T07:30:41+0200 DEBUG [ykman.descriptor.open_device:89] Opening driver for serial: None, type: YUBIKEY.YK4, mode: CCID

2019-07-31T07:30:41+0200 DEBUG [ykman.descriptor.open_device:91] Attempt 1 of 10

2019-07-31T07:30:41+0200 DEBUG [ykman.descriptor.open_device:110] Sleeping for 0.100000 s

2019-07-31T07:30:41+0200 DEBUG [ykman.descriptor.open_device:91] Attempt 2 of 10

2019-07-31T07:30:41+0200 DEBUG [ykman.descriptor.open_device:95] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x0000014C68EC85F8>, key_type: YUBIKEY.YK4, mode: CCID

2019-07-31T07:30:41+0200 DEBUG [ykman.device.__init__:198] Read config from device...

2019-07-31T07:30:41+0200 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00a4040008a000000527471117'

2019-07-31T07:30:41+0200 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'5669727475616c206d6772202d2046572076657273696f6e20342e332e349000'

2019-07-31T07:30:41+0200 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'001d000000'

2019-07-31T07:30:41+0200 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'0c01013f020400XXXXXX03013c9000'

2019-07-31T07:30:41+0200 DEBUG [ykman.device.__init__:200] Success!

2019-07-31T07:30:41+0200 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00a4040007a0000005272001'

2019-07-31T07:30:41+0200 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'0403040101008103000300XXXXXX9000'

2019-07-31T07:30:41+0200 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00a4040008a000000527471117'

2019-07-31T07:30:41+0200 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'5669727475616c206d6772202d2046572076657273696f6e20342e332e349000'

2019-07-31T07:30:41+0200 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'001611000406000000'

2019-07-31T07:30:41+0200 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'6d00'

2019-07-31T07:30:41+0200 DEBUG [ykman.cli.mode.mode:143] Failed to switch mode

Traceback (most recent call last):

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\driver_ccid.py", line 251, in set_mode

    self._set_mode_mgr(mode_data)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\driver_ccid.py", line 266, in _set_mode_mgr

    self.send_apdu(0, MGR_INS.SET_MODE, SLOT.DEVICE_CONFIG, 0, mode_data)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\driver_ccid.py", line 240, in send_apdu

    raise APDUError(resp, sw)

ykman.driver_ccid.APDUError: APDU error: SW=0x6d00



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\cli\mode.py", line 137, in mode

    dev.set_mode(mode, chalresp_timeout, autoeject)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\device.py", line 400, in set_mode

    autoeject_time)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\driver_ccid.py", line 253, in set_mode

    raise ModeSwitchError()

ykman.driver.ModeSwitchError: Failed to switch mode.
Failed to switch mode on the YubiKey. Make sure your YubiKey does not have an access code set.

2019-07-31T07:30:41+0200 DEBUG [ykman.driver_ccid.close:269] Close <ykman.driver_ccid.CCIDDriver object at 0x0000014C68EC85F8>
```

**ykneomgr.exe -d -M 6**
```
Trying reader 0: Yubico Yubikey 4 CCID 0

--> 13: 00 a4 04 00 08 a0 00 00 05 27 20 01 01

<-- 16: 04 03 04 01 01 00 81 03 00 03 00 XX XX XX 90 00

versionMajor 4

versionMinor 3

versionBuild 4

pgmSeq 1

touchLevel 256

mode 81

crTimeout 3

autoEjectTime 3

--> 4: 00 01 10 00

<-- 6: 00 XX XX XX 90 00

serialno XXXXXXX

81
```

**Comment by dagheyman** [comment]
Hi, thanks for the report. 

Yes, it's possible to get in this state on the YubiKey 4, by changing the mode, **NOT** removing and re-inserting the device, and then setting the OTP access code. I recommend contacting Yubico Support for anyone that accidentally does this.

For the YubiKey 5 series, the OTP access code no longer affects how USB transports can be configured, and this should not be possible.
