### ISSUE TITLE
CCIDError : Failled to transmit with protocol T1. Transaction failed.

### ISSUE THREAD

**Issue by Nobozoa** [Yubico/yubikey-manager#285]
- YubiKey Manager (ykman) version: 3.1.0
- How was it installed?: .pkg file from official website
- Operating system and version: 0SX 10.14.6
- YubiKey model and version: Yubikey 5C
- Bug description summary: 
Yubikey isn't detected by Yubikey Manager. When trying to use ykman for debug, i got an error when key is plugged in

Steps to reproduce
---

- Install yubikey-manager
- Set values into corresponding .vmx file (according to https://support.yubico.com/support/solutions/articles/15000008891-troubleshooting-vmware-workstation-device-passthrough)
- plug Yubikey in
- Accept the VM to take over control on this key
- see that the key is shown into about this mac > hardware > USB
- run yubikey-manager and see that the key doesnt show in
- Try to run /Applications/YubiKey\ Manager.app/Contents/MacOS/ykman list to list key

Expected result
---

Key is correctly detected by yubikey manager/ ykman doesnt crash 

Actual results and logs
---
qml: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ykman/driver_ccid.py", line 229, in send_apdu
    resp, sw1, sw2 = self._conn.transmit(header + body)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/smartcard/CardConnectionDecorator.py", line 82, in transmit
    return self.component.transmit(bytes, protocol)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/smartcard/CardConnection.py", line 146, in transmit
    data, sw1, sw2 = self.doTransmit(bytes, protocol)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/smartcard/pcsc/PCSCCardConnection.py", line 203, in doTransmit
    SCardGetErrorMessage(hresult))

smartcard.Exceptions.CardConnectionException: Failed to transmit with protocol T1. Transaction failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "qrc:///py/cli.py", line 12, in run
    return main()

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ykman/cli/__main__.py", line 260, in main
    cli(obj={})

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ykman/cli/config.py", line 243, in usb
    dev = ctx.obj['dev']

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ykman/cli/util.py", line 127, in __getitem__
    self.resolve()

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ykman/cli/util.py", line 124, in resolve
    self._objects[k] = f()

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ykman/cli/__main__.py", line 189, in resolve_device
    dev = _run_cmd_for_single(ctx, subcmd.name, transports, reader)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ykman/cli/__main__.py", line 128, in _run_cmd_for_single
    return descriptor.open_device(transports)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ykman/descriptor.py", line 97, in open_device
    dev = YubiKey(self, drv)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ykman/device.py", line 199, in __init__
    config = DeviceConfig(driver.read_config())

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ykman/driver_ccid.py", line 198, in read_config
    self.select(AID.MGR)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ykman/driver_ccid.py", line 243, in select
    return self.send_apdu(0, GP_INS_SELECT, 0x04, 0, aid)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ykman/driver_ccid.py", line 232, in send_apdu
    raise CCIDError(e)

ykman.driver_ccid.CCIDError: Failed to transmit with protocol T1. Transaction failed.

Other info
---

- It's in a VM using VMware
- I already set values in .vmx according to troubleshooting page for VMware
- The usb key is spotted in the mac hardware usb menu
- ykman got no error when key is unplugged 
- I tried restarting my VM but it changed nothing

**Comment by fdennis** [comment]
Hi,
Thanks for the report!
We have seen this error a few times. We will look into it.

**Comment by Nobozoa** [comment]
I have a bit more infos if that can be helpful : My key has been properly detected on an Ubuntu 18.10 VM and on my Mac VM, it is correctly detected with the personalization tool
