### ISSUE TITLE
`ykman list` breaks OATH driver for seconds after program exits

### ISSUE THREAD

**Issue by emlun** [Yubico/yubikey-manager#34]
- ykman version: 0.5.0
- Operating system and version: Arch Linux, kernel 4.14.8
- YubiKey model and version: NEO 3.4.9

Steps to reproduce
---

Run `ykman list && ykman oath info` - see end of post for output

Expected result
---

The program prints some information such as the OATH applet version of the YubiKey.

Actual results
---

The program crashes while trying to connect to the YubiKey.

Other info
---

- The issue appears with:
  - One YubiKey NEO plugged in
  - Two YubiKey NEO plugged in
  - One YubiKey NEO and one YubiKey 4 plugged in - but **not** if I swap the ports they're plugged into...
- The issue does not appear with one YubiKey 4 plugged in.
- The issue does not appear from repeated `ykman oath info` commands.
- The issue remains for 2-3 seconds after `ykman list` exits:
  - Fails: `ykman list && sleep 1 && ykman --device 4549848 oath info`
  - Fails: `ykman list && sleep 2 && ykman --device 4549848 oath info`
  - Succeeds: `ykman list && sleep 3 && ykman --device 4549848 oath info`
- Use case: In a script, in a loop over the serial numbers returned by `ykman list`.

Program output
---

With one YubiKey NEO plugged in:

```
$ ykman --log-level DEBUG list && ykman --log-level DEBUG oath info
2017-12-27T22:06:55+0100 DEBUG [ykman.descriptor.Descriptor.open_device:86] transports: 0x4, self.mode.transports: 0x7
2017-12-27T22:06:55+0100 DEBUG [ykman.descriptor.open_driver:141] Opening driver for serial: None, pid: PID.NEO_OTP_U2F_CCID
2017-12-27T22:06:55+0100 DEBUG [ykman.descriptor.open_driver:143] Attempt 1 of 3
2017-12-27T22:06:55+0100 DEBUG [ykman.driver_ccid.open_devices:243] Failed to connect to reader Yubico Yubikey NEO OTP+U2F+CCID 00 00
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ykman/driver_ccid.py", line 236, in open_devices
    conn.connect()
  File "/usr/lib/python3.6/site-packages/smartcard/CardConnectionDecorator.py", line 54, in connect
    self.component.connect(protocol, mode, disposition)
  File "/usr/lib/python3.6/site-packages/smartcard/pcsc/PCSCCardConnection.py", line 123, in connect
    SCardGetErrorMessage(hresult))
smartcard.Exceptions.NoCardException: ('Unable to connect to card or no card in reader', 'Unable to connect: No smart card inserted.')
2017-12-27T22:06:55+0100 DEBUG [ykman.descriptor.open_driver:161] Sleeping for 0.100000 s
2017-12-27T22:06:55+0100 DEBUG [ykman.descriptor.open_driver:143] Attempt 2 of 3
2017-12-27T22:06:55+0100 DEBUG [ykman.driver_ccid.open_devices:243] Failed to connect to reader Yubico Yubikey NEO OTP+U2F+CCID 00 00
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ykman/driver_ccid.py", line 236, in open_devices
    conn.connect()
  File "/usr/lib/python3.6/site-packages/smartcard/CardConnectionDecorator.py", line 54, in connect
    self.component.connect(protocol, mode, disposition)
  File "/usr/lib/python3.6/site-packages/smartcard/pcsc/PCSCCardConnection.py", line 123, in connect
    SCardGetErrorMessage(hresult))
smartcard.Exceptions.NoCardException: ('Unable to connect to card or no card in reader', 'Unable to connect: No smart card inserted.')
2017-12-27T22:06:55+0100 DEBUG [ykman.descriptor.open_driver:161] Sleeping for 0.200000 s
2017-12-27T22:06:55+0100 DEBUG [ykman.descriptor.open_driver:143] Attempt 3 of 3
2017-12-27T22:06:55+0100 DEBUG [ykman.driver_ccid.open_devices:243] Failed to connect to reader Yubico Yubikey NEO OTP+U2F+CCID 00 00
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ykman/driver_ccid.py", line 236, in open_devices
    conn.connect()
  File "/usr/lib/python3.6/site-packages/smartcard/CardConnectionDecorator.py", line 54, in connect
    self.component.connect(protocol, mode, disposition)
  File "/usr/lib/python3.6/site-packages/smartcard/pcsc/PCSCCardConnection.py", line 123, in connect
    SCardGetErrorMessage(hresult))
smartcard.Exceptions.NoCardException: ('Unable to connect to card or no card in reader', 'Unable to connect: No smart card inserted.')
2017-12-27T22:06:55+0100 DEBUG [ykman.descriptor.open_driver:161] Sleeping for 0.300000 s
2017-12-27T22:06:55+0100 DEBUG [ykman.descriptor.open_driver:163] No driver found for serial: None, pid: PID.NEO_OTP_U2F_CCID
Usage: ykman [OPTIONS] COMMAND [ARGS]...

Error: Failed connecting to the YubiKey.
```

**Comment by dainnilsson** [comment]
This is expected behavior unfortunately. The NEO can't keep state for more than one applet at once, and opening a connection to the device over one of the other transports (OTP or U2F, which the `list` command does) will cause the NEO to report that the smartcard has been ejected, and then reinserted once the device has been idle for a couple of seconds. During that time the smartcard is unavailable.

What we could do is detect this error specifically on a NEO, and wait up to 2-3 seconds and try again, hiding this issue from the user.
