### ISSUE TITLE
Command `ykman --device someserial otp info` crashes ykman

### ISSUE THREAD

**Issue by maiksensi** [Yubico/yubikey-manager#354]
- YubiKey Manager (ykman) version: 
```
YubiKey Manager (ykman) version: 3.1.1
Libraries:
    libykpers 1.20.0
    libusb 1.0.23
```

- How was it installed?: homebrew
- Operating system and version: MacOS: 
```
╰─$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101
```

- YubiKey model and version: Yubikey 5ci
- Bug description summary:
`ykman crashes when running ykman --device someserial otp info`

Steps to reproduce
---
Run `ykman --log-level DEBUG --device SOMESERIAL otp info`

[Expected Result]
---
--> I should see info about otp 

Actual results and logs
---
``` bash
╰─$ ykman --log-level DEBUG --device  SOMESERIAL otp info                                                                                                              130 ↵
2020-08-10T10:10:22+0200 INFO [ykman.logging_setup.setup:58] Initialized logging for ykman version: 3.1.1
2020-08-10T10:10:22+0200 DEBUG [ykman.descriptor._open_driver:175] Opening driver for transports: TRANSPORT.OTP, serial: 14412874, key_type: None, mode: None
2020-08-10T10:10:22+0200 DEBUG [ykman.descriptor._open_driver:179] Attempt 1 of 10
2020-08-10T10:10:22+0200 DEBUG [ykman.driver_otp.open_devices:222] Failed to open key at position 0
2020-08-10T10:10:22+0200 DEBUG [ykman.descriptor._open_driver:202] Sleeping for 0.100000 s
2020-08-10T10:10:22+0200 DEBUG [ykman.descriptor._open_driver:204] No driver found for serial: SOMESERIAL, key_type: None, mode: None
2020-08-10T10:10:22+0200 DEBUG [ykman.descriptor._open_driver:179] Attempt 2 of 10
2020-08-10T10:10:22+0200 DEBUG [ykman.driver_otp.open_devices:222] Failed to open key at position 0
2020-08-10T10:10:22+0200 DEBUG [ykman.descriptor._open_driver:202] Sleeping for 0.200000 s
2020-08-10T10:10:22+0200 DEBUG [ykman.descriptor._open_driver:204] No driver found for serial: SOMESERIAL, key_type: None, mode: None
2020-08-10T10:10:22+0200 DEBUG [ykman.descriptor._open_driver:179] Attempt 3 of 10
2020-08-10T10:10:22+0200 DEBUG [ykman.driver_otp.open_devices:222] Failed to open key at position 0
2020-08-10T10:10:22+0200 DEBUG [ykman.descriptor._open_driver:202] Sleeping for 0.300000 s
2020-08-10T10:10:22+0200 DEBUG [ykman.descriptor._open_driver:204] No driver found for serial: SOMESERIAL, key_type: None, mode: None
2020-08-10T10:10:22+0200 DEBUG [ykman.descriptor._open_driver:179] Attempt 4 of 10
2020-08-10T10:10:22+0200 DEBUG [ykman.driver_otp.open_devices:222] Failed to open key at position 0
2020-08-10T10:10:22+0200 DEBUG [ykman.descriptor._open_driver:202] Sleeping for 0.400000 s
2020-08-10T10:10:23+0200 DEBUG [ykman.descriptor._open_driver:204] No driver found for serial: SOMESERIAL, key_type: None, mode: None
2020-08-10T10:10:23+0200 DEBUG [ykman.descriptor._open_driver:179] Attempt 5 of 10
2020-08-10T10:10:23+0200 DEBUG [ykman.driver_otp.open_devices:222] Failed to open key at position 0
2020-08-10T10:10:23+0200 DEBUG [ykman.descriptor._open_driver:202] Sleeping for 0.500000 s
2020-08-10T10:10:23+0200 DEBUG [ykman.descriptor._open_driver:204] No driver found for serial: SOMESERIAL, key_type: None, mode: None
2020-08-10T10:10:23+0200 DEBUG [ykman.descriptor._open_driver:179] Attempt 6 of 10
2020-08-10T10:10:23+0200 DEBUG [ykman.driver_otp.open_devices:222] Failed to open key at position 0
2020-08-10T10:10:23+0200 DEBUG [ykman.descriptor._open_driver:202] Sleeping for 0.600000 s
2020-08-10T10:10:24+0200 DEBUG [ykman.descriptor._open_driver:204] No driver found for serial: SOMESERIAL, key_type: None, mode: None
2020-08-10T10:10:24+0200 DEBUG [ykman.descriptor._open_driver:179] Attempt 7 of 10
2020-08-10T10:10:24+0200 DEBUG [ykman.driver_otp.open_devices:222] Failed to open key at position 0
2020-08-10T10:10:24+0200 DEBUG [ykman.descriptor._open_driver:202] Sleeping for 0.700000 s
2020-08-10T10:10:25+0200 DEBUG [ykman.descriptor._open_driver:204] No driver found for serial: SOMESERIAL, key_type: None, mode: None
2020-08-10T10:10:25+0200 DEBUG [ykman.descriptor._open_driver:179] Attempt 8 of 10
2020-08-10T10:10:25+0200 DEBUG [ykman.driver_otp.open_devices:222] Failed to open key at position 0
2020-08-10T10:10:25+0200 DEBUG [ykman.descriptor._open_driver:202] Sleeping for 0.800000 s
2020-08-10T10:10:25+0200 DEBUG [ykman.descriptor._open_driver:204] No driver found for serial: SOMESERIAL, key_type: None, mode: None
2020-08-10T10:10:25+0200 DEBUG [ykman.descriptor._open_driver:179] Attempt 9 of 10
2020-08-10T10:10:25+0200 DEBUG [ykman.driver_otp.open_devices:222] Failed to open key at position 0
2020-08-10T10:10:25+0200 DEBUG [ykman.descriptor._open_driver:202] Sleeping for 0.900000 s
2020-08-10T10:10:26+0200 DEBUG [ykman.descriptor._open_driver:204] No driver found for serial: SOMESERIAL, key_type: None, mode: None
2020-08-10T10:10:26+0200 DEBUG [ykman.descriptor._open_driver:179] Attempt 10 of 10
2020-08-10T10:10:26+0200 DEBUG [ykman.driver_otp.open_devices:222] Failed to open key at position 0
2020-08-10T10:10:26+0200 DEBUG [ykman.descriptor._open_driver:202] Sleeping for 1.000000 s
2020-08-10T10:10:27+0200 DEBUG [ykman.descriptor._open_driver:204] No driver found for serial: SOMESERIAL, key_type: None, mode: None
2020-08-10T10:10:27+0200 DEBUG [ykman.descriptor._open_driver:175] Opening driver for transports: 7, serial: SOMESERIAL, key_type: None, mode: None
2020-08-10T10:10:27+0200 DEBUG [ykman.descriptor._open_driver:179] Attempt 1 of 10
2020-08-10T10:10:27+0200 DEBUG [ykman.device.__init__:198] Read config from device...
2020-08-10T10:10:27+0200 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00a4040008a000000527471117'
2020-08-10T10:10:27+0200 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'5669727475616c206d6772202d2046572076657273696f6e20352e322e369000'
2020-08-10T10:10:27+0200 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'001d000000'
2020-08-10T10:10:27+0200 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'260102023f0302023f020400dbec4a04010505030502060602000007010f0801000a01000f010c9000'
2020-08-10T10:10:27+0200 DEBUG [ykman.device.__init__:200] Success!
2020-08-10T10:10:27+0200 DEBUG [ykman.device.__init__:289] Identified YubiKey 5
2020-08-10T10:10:27+0200 DEBUG [ykman.descriptor._open_driver:182] Found driver: <ykman.driver_ccid.CCIDDriver object at 0x10fefdac0> serial: 14412874, key_type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2020-08-10T10:10:27+0200 DEBUG [ykman.device.__init__:198] Read config from device...
2020-08-10T10:10:27+0200 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00a4040008a000000527471117'
2020-08-10T10:10:27+0200 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'5669727475616c206d6772202d2046572076657273696f6e20352e322e369000'
2020-08-10T10:10:27+0200 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'001d000000'
2020-08-10T10:10:27+0200 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'260102023f0302023f020400dbec4a04010505030502060602000007010f0801000a01000f010c9000'
2020-08-10T10:10:27+0200 DEBUG [ykman.device.__init__:200] Success!
2020-08-10T10:10:27+0200 DEBUG [ykman.device.__init__:289] Identified YubiKey 5
2020-08-10T10:10:27+0200 DEBUG [ykman.driver_ccid.__del__:273] Destroy <ykman.driver_ccid.CCIDDriver object at 0x10fefdac0>
2020-08-10T10:10:27+0200 DEBUG [ykman.driver_ccid.close:269] Close <ykman.driver_ccid.CCIDDriver object at 0x10fefdac0>
Traceback (most recent call last):
  File "/usr/local/bin/ykman", line 11, in <module>
    load_entry_point('yubikey-manager==3.1.1', 'console_scripts', 'ykman')()
  File "/usr/local/Cellar/ykman/3.1.1_1/libexec/lib/python3.8/site-packages/ykman/cli/__main__.py", line 273, in main
    cli(obj={})
  File "/usr/local/Cellar/ykman/3.1.1_1/libexec/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/ykman/3.1.1_1/libexec/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/ykman/3.1.1_1/libexec/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/ykman/3.1.1_1/libexec/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/ykman/3.1.1_1/libexec/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/ykman/3.1.1_1/libexec/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/ykman/3.1.1_1/libexec/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/ykman/3.1.1_1/libexec/lib/python3.8/site-packages/ykman/cli/otp.py", line 151, in info
    dev = ctx.obj['dev']
  File "/usr/local/Cellar/ykman/3.1.1_1/libexec/lib/python3.8/site-packages/ykman/cli/util.py", line 127, in __getitem__
    self.resolve()
  File "/usr/local/Cellar/ykman/3.1.1_1/libexec/lib/python3.8/site-packages/ykman/cli/util.py", line 124, in resolve
    self._objects[k] = f()
  File "/usr/local/Cellar/ykman/3.1.1_1/libexec/lib/python3.8/site-packages/ykman/cli/__main__.py", line 195, in resolve_device
    ctx.call_on_close(dev.close)
AttributeError: 'NoneType' object has no attribute 'close'
```

Other info
---

Input monitoring is enabled in security settings.

**Comment by trebortech** [comment]
@maiksensi How many digits are the serial numbers of the YubiKeys that you have plugged in?

**Comment by DBX12** [comment]
I have exactly the same issue, my device serial is 8 digits long.

**Comment by trebortech** [comment]
Try this

Update https://github.com/Yubico/yubikey-manager/blob/70ef490687d8aa251437a04a9bc6c18f488a1c56/ykman/driver_otp.py#L122

```
def read_version(self):
    if self._version[0] == 3:  # This is the OTP applet version.
        return None
    return self._version
```
to 

```
def read_version(self):
    return self._version
```

**Comment by dainnilsson** [comment]
I don't think this is related to the number of digits in the serial number. From what I can see, the original log output shows a failure to connect to the key over the OTP (keyboard) interface. It looks like it might be permissions related. I know that recent versions of MacOS have become more strict on accessing USB keyboards, often prompting the user for permission though a dialog. We've also seen issues in the past when Mac users have other software running which can interfere with this, such as Karabiner.

@DBX12 - Are you also trying to invoke `ykman otp`, or is it a different command causing problems for you? What OS are you running?

**Comment by DBX12** [comment]
Yes, I'm also invoking `ykman otp`, I attach my log. I think it has to do with permissions, as it works while running it with sudo.
I'm running Linux Mint 20 which is based on Debian 11 (Bullseye). `uname -a` reads: `Linux DBX12 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

---

As user:
```
dbx12@DBX12:~$ ykman --log-level DEBUG otp info
2020-11-26T09:04:26+0100 INFO [ykman.logging_setup.setup:58] Initialized logging for ykman version: 3.1.1
2020-11-26T09:04:26+0100 DEBUG [ykman.descriptor.Descriptor.open_device:86] transports: 0x1, self.mode.transports: 0x7
2020-11-26T09:04:26+0100 DEBUG [ykman.descriptor.open_device:91] Opening driver for serial: None, type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2020-11-26T09:04:26+0100 DEBUG [ykman.descriptor.open_device:94] Attempt 1 of 10
2020-11-26T09:04:26+0100 DEBUG [ykman.driver_otp.open_devices:222] Failed to open key at position 0
2020-11-26T09:04:26+0100 DEBUG [ykman.descriptor.open_device:113] Sleeping for 0.100000 s
2020-11-26T09:04:26+0100 DEBUG [ykman.descriptor.open_device:94] Attempt 2 of 10
2020-11-26T09:04:26+0100 DEBUG [ykman.driver_otp.open_devices:222] Failed to open key at position 0
2020-11-26T09:04:26+0100 DEBUG [ykman.descriptor.open_device:113] Sleeping for 0.200000 s
2020-11-26T09:04:26+0100 DEBUG [ykman.descriptor.open_device:94] Attempt 3 of 10
2020-11-26T09:04:26+0100 DEBUG [ykman.driver_otp.open_devices:222] Failed to open key at position 0
2020-11-26T09:04:26+0100 DEBUG [ykman.descriptor.open_device:113] Sleeping for 0.300000 s
2020-11-26T09:04:27+0100 DEBUG [ykman.descriptor.open_device:94] Attempt 4 of 10
2020-11-26T09:04:27+0100 DEBUG [ykman.driver_otp.open_devices:222] Failed to open key at position 0
2020-11-26T09:04:27+0100 DEBUG [ykman.descriptor.open_device:113] Sleeping for 0.400000 s
2020-11-26T09:04:27+0100 DEBUG [ykman.descriptor.open_device:94] Attempt 5 of 10
2020-11-26T09:04:27+0100 DEBUG [ykman.driver_otp.open_devices:222] Failed to open key at position 0
2020-11-26T09:04:27+0100 DEBUG [ykman.descriptor.open_device:113] Sleeping for 0.500000 s
2020-11-26T09:04:28+0100 DEBUG [ykman.descriptor.open_device:94] Attempt 6 of 10
2020-11-26T09:04:28+0100 DEBUG [ykman.driver_otp.open_devices:222] Failed to open key at position 0
2020-11-26T09:04:28+0100 DEBUG [ykman.descriptor.open_device:113] Sleeping for 0.600000 s
2020-11-26T09:04:28+0100 DEBUG [ykman.descriptor.open_device:94] Attempt 7 of 10
2020-11-26T09:04:28+0100 DEBUG [ykman.driver_otp.open_devices:222] Failed to open key at position 0
2020-11-26T09:04:28+0100 DEBUG [ykman.descriptor.open_device:113] Sleeping for 0.700000 s
2020-11-26T09:04:29+0100 DEBUG [ykman.descriptor.open_device:94] Attempt 8 of 10
2020-11-26T09:04:29+0100 DEBUG [ykman.driver_otp.open_devices:222] Failed to open key at position 0
2020-11-26T09:04:29+0100 DEBUG [ykman.descriptor.open_device:113] Sleeping for 0.800000 s
2020-11-26T09:04:30+0100 DEBUG [ykman.descriptor.open_device:94] Attempt 9 of 10
2020-11-26T09:04:30+0100 DEBUG [ykman.driver_otp.open_devices:222] Failed to open key at position 0
2020-11-26T09:04:30+0100 DEBUG [ykman.descriptor.open_device:113] Sleeping for 0.900000 s
2020-11-26T09:04:31+0100 DEBUG [ykman.descriptor.open_device:94] Attempt 10 of 10
2020-11-26T09:04:31+0100 DEBUG [ykman.driver_otp.open_devices:222] Failed to open key at position 0
2020-11-26T09:04:31+0100 DEBUG [ykman.descriptor.open_device:113] Sleeping for 1.000000 s
2020-11-26T09:04:32+0100 DEBUG [ykman.descriptor.open_device:115] No matching device found
Usage: ykman [OPTIONS] COMMAND [ARGS]...
Try "ykman -h" for help.

Error: Failed connecting to YubiKey 5 [OTP+FIDO+CCID]. Make sure the application have                     the required permissions.
```
With sudo:
```
dbx12@DBX12:~$ sudo ykman --log-level DEBUG otp info
2020-11-26T09:05:37+0100 INFO [ykman.logging_setup.setup:58] Initialized logging for ykman version: 3.1.1
2020-11-26T09:05:37+0100 DEBUG [ykman.descriptor.Descriptor.open_device:86] transports: 0x1, self.mode.transports: 0x7
2020-11-26T09:05:37+0100 DEBUG [ykman.descriptor.open_device:91] Opening driver for serial: None, type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2020-11-26T09:05:37+0100 DEBUG [ykman.descriptor.open_device:94] Attempt 1 of 10
2020-11-26T09:05:37+0100 DEBUG [ykman.driver_otp.open_devices:224] Success in opening key at position 0
2020-11-26T09:05:37+0100 DEBUG [ykman.descriptor.open_device:97] Found driver: <ykman.driver_otp.OTPDriver object at 0x7f10121ef7f0>, key_type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2020-11-26T09:05:37+0100 DEBUG [ykman.device.__init__:198] Read config from device...
2020-11-26T09:05:38+0100 DEBUG [ykman.driver_otp.read_config:146] Failed reading config.OTP interface might be locked, try waiting 3 seconds...
2020-11-26T09:05:41+0100 DEBUG [ykman.device.__init__:200] Success!
2020-11-26T09:05:41+0100 DEBUG [ykman.device.__init__:289] Identified YubiKey 5
Slot 1: programmed
Slot 2: empty
2020-11-26T09:05:41+0100 DEBUG [ykman.driver_otp.close:203] Close <ykman.driver_otp.OTPDriver object at 0x7f10121ef7f0>
2020-11-26T09:05:41+0100 DEBUG [ykman.driver_otp.__del__:208] Destroy <ykman.driver_otp.OTPDriver object at 0x7f10121ef7f0>
```

**Comment by nevun** [comment]
@DBX12 have you configured your udev rules so your user can access the hid device? see https://support.yubico.com/hc/en-us/articles/360013708900-Using-Your-U2F-YubiKey-with-Linux

**Comment by DBX12** [comment]
I checked, the rules were missing, seems like I forgot to install them but it did not provide any change. I also checked my group memberships before rebooting, I'm in `plugdev` and the hardware id / vendor id match my yubikey. The log output seems identical to the one posted above.

**Comment by dainnilsson** [comment]
@DBX12 can you try the Udev rules from [here](https://github.com/Yubico/yubikey-personalization) instead (instructions in the README under "Using")?

**Comment by ProfessorSalty** [comment]
I'm running into the same problem when I try to run `ykman -l DEBUG piv info`

```
2021-04-06T21:49:11-0400 INFO [ykman.logging_setup.setup:58] Initialized logging for ykman version: 3.1.1
2021-04-06T21:49:11-0400 DEBUG [ykman.descriptor.Descriptor.open_device:86] transports: 0x4, self.mode.transports: 0x7
2021-04-06T21:49:11-0400 DEBUG [ykman.descriptor.open_device:91] Opening driver for serial: None, type: YUBIKEY.YK4, mode: OTP+FIDO+CCID
2021-04-06T21:49:11-0400 DEBUG [ykman.descriptor.open_device:94] Attempt 1 of 10
2021-04-06T21:49:11-0400 DEBUG [ykman.descriptor.open_device:113] Sleeping for 0.100000 s
2021-04-06T21:49:11-0400 DEBUG [ykman.descriptor.open_device:94] Attempt 2 of 10
2021-04-06T21:49:11-0400 DEBUG [ykman.descriptor.open_device:113] Sleeping for 0.200000 s
2021-04-06T21:49:12-0400 DEBUG [ykman.descriptor.open_device:94] Attempt 3 of 10
2021-04-06T21:49:12-0400 DEBUG [ykman.descriptor.open_device:113] Sleeping for 0.300000 s
2021-04-06T21:49:12-0400 DEBUG [ykman.descriptor.open_device:94] Attempt 4 of 10
2021-04-06T21:49:12-0400 DEBUG [ykman.descriptor.open_device:113] Sleeping for 0.400000 s
2021-04-06T21:49:12-0400 DEBUG [ykman.descriptor.open_device:94] Attempt 5 of 10
2021-04-06T21:49:12-0400 DEBUG [ykman.descriptor.open_device:113] Sleeping for 0.500000 s
2021-04-06T21:49:13-0400 DEBUG [ykman.descriptor.open_device:94] Attempt 6 of 10
2021-04-06T21:49:13-0400 DEBUG [ykman.descriptor.open_device:113] Sleeping for 0.600000 s
2021-04-06T21:49:14-0400 DEBUG [ykman.descriptor.open_device:94] Attempt 7 of 10
2021-04-06T21:49:14-0400 DEBUG [ykman.descriptor.open_device:113] Sleeping for 0.700000 s
2021-04-06T21:49:14-0400 DEBUG [ykman.descriptor.open_device:94] Attempt 8 of 10
2021-04-06T21:49:14-0400 DEBUG [ykman.descriptor.open_device:113] Sleeping for 0.800000 s
2021-04-06T21:49:15-0400 DEBUG [ykman.descriptor.open_device:94] Attempt 9 of 10
2021-04-06T21:49:15-0400 DEBUG [ykman.descriptor.open_device:113] Sleeping for 0.900000 s
2021-04-06T21:49:16-0400 DEBUG [ykman.descriptor.open_device:94] Attempt 10 of 10
2021-04-06T21:49:16-0400 DEBUG [ykman.descriptor.open_device:113] Sleeping for 1.000000 s
2021-04-06T21:49:17-0400 DEBUG [ykman.descriptor.open_device:115] No matching device found
Usage: ykman [OPTIONS] COMMAND [ARGS]...
Try "ykman -h" for help.

Error: Failed connecting to YubiKey 5 [OTP+FIDO+CCID]. Make sure the application have                     the required permissions.
```

I set up my Yubikey by following the instructions [herer](https://smallstep.com/blog/build-a-tiny-ca-with-raspberry-pi-yubikey/), so my udev rules are

```
# /etc/udev/rules.d/75-yubikey.rules
ACTION=="add", SUBSYSTEM=="usb", ENV{PRODUCT}=="1050/407/*", TAG+="systemd", SYMLINK+="yubikey"
ACTION=="remove", SUBSYSTEM=="usb", ENV{PRODUCT}=="1050/407/*", TAG+="systemd"
```

I've also tried the [rules linked to above](https://github.com/Yubico/yubikey-personalization), but nothing changed. I remember being able to run the command successfully last week, but I don't remember what I have changed in the meantime to have broken it.

```
~> ykman --version 
YubiKey Manager (ykman) version: 3.1.1
Libraries:
    libykpers 1.20.0
    libusb 1.0.23
```
```
~> uname -r
5.4.0-1032-raspi
```

**Comment by dainnilsson** [comment]
@ProfessorSalty - PIV uses PC/SC for communication, so neither of those Udev rules will be relevant for that. Make sure you have pcscd installed and running. I'd also recommend you upgrade ykman to version 4.0 (4.0.1 is current).

**Comment by dainnilsson** [comment]
Closing due to inactivity, feel free to reopen if needed.
