### ISSUE TITLE
AttributeError: '_Ed25519PrivateKey' object has no attribute 'key_size'

### ISSUE THREAD

**Issue by yawnt** [Yubico/yubikey-manager#361]
- YubiKey Manager (ykman) version: 3.1.1
- How was it installed?: ArchLinux AUR
- Operating system and version: ArchLinux (5.8.10)
- YubiKey model and version: Yubikey 5 NFC (5.2.6)
- Bug description summary: ykman throws AttributeError when importing .pem key

Steps to reproduce
---

```
$ openssl genpkey -algorithm Ed25519 -out ca.pem
$ ykman piv import-key 9a ca.pem
```

Expected result
---

Key is imported into slot 9A

Actual results and logs
---

```
$ ykman piv import-key 9a ca.pem
Enter PIN: 
Traceback (most recent call last):
  File "/usr/bin/ykman", line 33, in <module>
    sys.exit(load_entry_point('yubikey-manager==3.1.1', 'console_scripts', 'ykman')())
  File "/usr/lib/python3.8/site-packages/ykman/cli/__main__.py", line 273, in main
    cli(obj={})
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/ykman/cli/piv.py", line 411, in import_key
    _check_key_size(ctx, controller, private_key)
  File "/usr/lib/python3.8/site-packages/ykman/cli/piv.py", line 982, in _check_key_size
    if (private_key.key_size == 1024
AttributeError: '_Ed25519PrivateKey' object has no attribute 'key_size'
```

**Comment by nevun** [comment]
That error message is maybe not the best one..

The PIV standard does not yet support Ed25519.

So maybe use one of the supported algorithms instead, like the P-384:  
`$ openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-384 -out ca.pem`

**Comment by dainnilsson** [comment]
Agreed, we need to add some better error handling around that!

**Comment by yawnt** [comment]
> That error message is maybe not the best one..
> 
> The PIV standard does not yet support Ed25519.
> 
> So maybe use one of the supported algorithms instead, like the P-384:
> `$ openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-384 -out ca.pem`

Thank you for your prompt reply! I thought it was because it's in the [PKCS#11 v3 standard](https://docs.oasis-open.org/pkcs11/pkcs11-curr/v3.0/csprd01/pkcs11-curr-v3.0-csprd01.html#_Toc10560880).

I can close the issue or leave it open if you want to close it after the better error handling is added.

**Comment by dainnilsson** [comment]
Thanks. Let's leave it open for now as a reminder to deal with the error handling.
