### ISSUE TITLE
Ykman cli freezes on any command

### ISSUE THREAD

**Issue by aleksanderaleksic** [Yubico/yubikey-manager#367]
- YubiKey Manager (ykman) version: 3.1.1
- How was it installed?: `sudo apt install yubikey-manager`
- Operating system and version: Ubuntu 20.10 
- YubiKey model and version: 5C NFC and 4
- Bug description summary: What ever command you pass inn it freezes. A rebbot is required to temporarly solve it.

Steps to reproduce
---
Ykman works fine for a long time but after suddently when i run `ykman oauth code ...` it freezes.
I also tried to run `ykman` (without any commands) and it still freezes.

Expected results
---
I expected to get the code from the oath command.
Or to get the help ouput

Actual results and logs
---
When i do `ctrl + c` i get:
```
^CTraceback (most recent call last):
  File "/usr/bin/ykman", line 11, in <module>
    load_entry_point('yubikey-manager==3.1.1', 'console_scripts', 'ykman')()
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 473, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/ykman/cli/__main__.py", line 36, in <module>
    from ..driver_otp import libversion as ykpers_version
  File "/usr/lib/python3/dist-packages/ykman/driver_otp.py", line 48, in <module>
    if not ykpers.yk_init():
KeyboardInterrupt
```

Other info
---
To temporarly resolve this I need to restart my machine, closing the terminal or the.
This happens regardless of wheather a yubikey is connected or not.

**Comment by dainnilsson** [comment]
That's a strange error, I haven't seen that happen before. It looks like it is somehow related to communication with the libykpers library, which seems to be getting stuck for some reason. If you're feeling adventurous I would suggest seeing if you can run from the `next` branch, which no longer uses the libykpers library.

**Comment by aleksanderaleksic** [comment]
@dainnilsson Thanks I will try that out and let you know if that helped.

**Comment by dainnilsson** [comment]
Closing due to inactivity. Hopefully this is no longer an issue in ykman 4.0.
