### ISSUE TITLE
TypeError: list_devices() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by konstantinkostin28** [Yubico/yubikey-manager#380]
- YubiKey Manager (ykman) version:
```
YubiKey Manager (ykman) version: 3.1.1
Libraries:
    libykpers 1.18.0
    libusb 1.0.2
```
- How was it installed?:
```
pip3 install yubikey-manager
```
- Operating system and version: Ubuntu 18.04
- YubiKey model and version: Yubikey 5 NFC
- Bug description summary: "ykman fido ..." command fails with python error

Steps to reproduce
---

Install fresh version of ykman and fido2 package.
Run: ```ykman fido info```

Expected result
---

Actual results and logs
---

$ ykman fido info
Traceback (most recent call last):
  File "/home/user/.local/bin/ykman", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/ykman/cli/__main__.py", line 273, in main
    cli(obj={})
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/ykman/cli/fido.py", line 87, in info
    controller = ctx.obj['controller']
  File "/home/user/.local/lib/python3.6/site-packages/ykman/cli/util.py", line 127, in __getitem__
    self.resolve()
  File "/home/user/.local/lib/python3.6/site-packages/ykman/cli/util.py", line 124, in resolve
    self._objects[k] = f()
  File "/home/user/.local/lib/python3.6/site-packages/ykman/cli/__main__.py", line 194, in resolve_device
    dev = _run_cmd_for_single(ctx, subcmd.name, transports, reader)
  File "/home/user/.local/lib/python3.6/site-packages/ykman/cli/__main__.py", line 132, in _run_cmd_for_single
    return descriptor.open_device(transports)
  File "/home/user/.local/lib/python3.6/site-packages/ykman/descriptor.py", line 96, in open_device
    for drv in _list_drivers(transports):
  File "/home/user/.local/lib/python3.6/site-packages/ykman/descriptor.py", line 164, in _list_drivers
    for dev in open_fido():
  File "/home/user/.local/lib/python3.6/site-packages/ykman/driver_fido.py", line 97, in open_devices
    for dev in CtapHidDevice.list_devices(descriptor_filter):
TypeError: list_devices() takes 1 positional argument but 2 were given

Other info
---

Looks like [fido2](https://pypi.org/project/fido2) package has been updated recently and API was changed.
I just uninstalled fido2==0.9.0 and installed fido2==0.8.1 and ykman started to work again

**Comment by dainnilsson** [comment]
yubikey-manager 3.1.2 was released a couple of days ago to address this by locking the python-fido2 dependency to <0.9. Later we will release a new version which is compatible with python-fido2 0.9.
