### ISSUE TITLE
Legacy Yubikey NEO-n not detected by ykman

### ISSUE THREAD

**Issue by khimaros** [Yubico/yubikey-manager#383]
- YubiKey Manager (ykman) version: 3.1.1
- How was it installed?: `apt install`
- Operating system and version: debian bullseye
- YubiKey model and version: Legacy Yubikey NEO-n
- Bug description summary: Legacy Yubikey NEO-n not detected by ykman

Steps to reproduce
---

i'm able to reproduce 100% of the time.

1. insert the Legacy Yubikey NEO-n
2. run `ykman info`

Expected result
---

key is listed in the output

Actual results and logs
---

```
$ ykman info
Error: No YubiKey detected!
```

Other info
---

the key is completely functional in Firefox and Chromium.

**Comment by dainnilsson** [comment]
Would you be able to test the 4.0 alpha version of ykman to see if this issue still persists?

**Comment by khimaros** [comment]
@dainnilsson -- thank you for the reply.

here's the output from ykman in Git main:

```
2021-02-15T08:11:50-0800 ERROR [ykman.cli.__main__.main:365] Error
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/ykman/cli/__main__.py", line 356, in main
    cli(obj={})
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/ykman/cli/info.py", line 157, in info
    info = ctx.obj["info"]
  File "/home/user/.local/lib/python3.9/site-packages/ykman/cli/util.py", line 174, in __getitem__
    self.resolve()
  File "/home/user/.local/lib/python3.9/site-packages/ykman/cli/util.py", line 171, in resolve
    self._objects[k] = f()
  File "/home/user/.local/lib/python3.9/site-packages/ykman/cli/__main__.py", line 283, in <lambda>
    ctx.obj.add_resolver("conn", lambda: resolve()[0])
  File "/home/user/.local/lib/python3.9/site-packages/ykman/cli/__main__.py", line 277, in resolve
    resolve.items = _run_cmd_for_single(
  File "/home/user/.local/lib/python3.9/site-packages/ykman/cli/__main__.py", line 161, in _run_cmd_for_single
    devices, state = scan_devices()
  File "/home/user/local/lib/python3.9/site-packages/ykman/device.py", line 107, in scan_devices
    devs = list_devs()
  File "/home/user/.local/lib/python3.9/site-packages/ykman/hid/__init__.py", line 68, in list_ctap_devices
    return [CtapYubiKeyDevice(d) for d in list_descriptors()]
  File "/home/user/.local/lib/python3.9/site-packages/ykman/hid/__init__.py", line 68, in <listcomp>
    return [CtapYubiKeyDevice(d) for d in list_descriptors()]
  File "/home/user/.local/lib/python3.9/site-packages/ykman/hid/__init__.py", line 54, in __init__
    TRANSPORT.USB, descriptor.path, PID(descriptor.pid)
  File "/usr/lib/python3.9/enum.py", line 360, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.9/enum.py", line 677, in __new__
    raise ve_exc
ValueError: 512 is not a valid PID
Error: 512 is not a valid PID
```

**Comment by dainnilsson** [comment]
Based on this error, it doesn't actually look like you have a YubiKey. PID 512 (0x200) is the Product ID of a Google-specific device (Gnubby) which is not supported by this tool.

**Comment by khimaros** [comment]
that makes sense. thank you for following up.
