### ISSUE TITLE
NotSupportedError -> bricked with ykman

### ISSUE THREAD

**Issue by ulrichard** [Yubico/yubikey-manager#387]
- YubiKey Manager (ykman) version: 3.1.1
- How was it installed?: apt
- Operating system and version: Ubuntu groovy
- YubiKey model and version:  Neo
- Bug description summary:  NotSupportedError -> bricked with ykman

Steps to reproduce
---

When I ran a script for provisioning a new Yubikey for PIV, I had accidentially still my private Yubikey plugged in. Since then my private YubiKey doesn't respond any more.

Here are some of the commands that were in the script:
...
ykman piv reset -f
yubico-piv-tool -a import-certificate -s 9c < ${certificatePath}
yubico-piv-tool -a import-key -s 9c --touch-policy=always  < ${privateKeyPath}
ykman piv set-pin-retries -P 123456 -m ${management_key} -f 3 3
ykman piv change-puk -p 12345678
ykman piv change-pin -P 123456
ykman config usb --disable OTP -f
ykman config usb --disable U2F -f
ykman config usb --disable OpenPGP -f
ykman config usb --disable OATH -f
ykman config usb --disable FIDO2 -f
ykman config nfc --disable-all -f
ykman piv info
...

Since I use my private Yubikey for GPG/TOTP/OTP but not for anything PIV related, I thought it should not be affected by the PIV commands. As soon as I realized my mistake, I tried re-enabling the other services with "ykman config usb --enable-all" but it didn't help.

When I execute gpg or ykman commands, the LED is still blinking, but then comes back with an error.

This is what I get from the device now:

$ lsusb
Bus 001 Device 059: ID 1050:0112 Yubico.com Yubikey NEO(-N) CCID

$ gpg --card-status
gpg: selecting card failed: Kein passendes Gerät gefunden
gpg: OpenPGP Karte ist nicht vorhanden: Kein passendes Gerät gefunden

$ ykman info
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ykman/device.py", line 199, in __init__
    config = DeviceConfig(driver.read_config())
  File "/usr/lib/python3/dist-packages/ykman/driver_ccid.py", line 197, in read_config
    raise NotSupportedError()
ykman.driver.NotSupportedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ykman", line 11, in <module>
    load_entry_point('yubikey-manager==3.1.1', 'console_scripts', 'ykman')()
  File "/usr/lib/python3/dist-packages/ykman/cli/__main__.py", line 273, in main
    cli(obj={})
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3/dist-packages/ykman/cli/info.py", line 137, in info
    dev = ctx.obj['dev']
  File "/usr/lib/python3/dist-packages/ykman/cli/util.py", line 127, in __getitem__
    self.resolve()
  File "/usr/lib/python3/dist-packages/ykman/cli/util.py", line 124, in resolve
    self._objects[k] = f()
  File "/usr/lib/python3/dist-packages/ykman/cli/__main__.py", line 194, in resolve_device
    dev = _run_cmd_for_single(ctx, subcmd.name, transports, reader)
  File "/usr/lib/python3/dist-packages/ykman/cli/__main__.py", line 132, in _run_cmd_for_single
    return descriptor.open_device(transports)
  File "/usr/lib/python3/dist-packages/ykman/descriptor.py", line 99, in open_device
    dev = YubiKey(self, drv)
  File "/usr/lib/python3/dist-packages/ykman/device.py", line 219, in __init__
    serial = driver.read_serial()
  File "/usr/lib/python3/dist-packages/ykman/driver_ccid.py", line 178, in read_serial
    self.select(AID.OTP)
  File "/usr/lib/python3/dist-packages/ykman/driver_ccid.py", line 243, in select
    return self.send_apdu(0, GP_INS_SELECT, 0x04, 0, aid)
  File "/usr/lib/python3/dist-packages/ykman/driver_ccid.py", line 229, in send_apdu
    resp, sw1, sw2 = self._conn.transmit(header + body)
  File "/usr/lib/python3/dist-packages/smartcard/CardConnectionDecorator.py", line 82, in transmit
    return self.component.transmit(bytes, protocol)
  File "/usr/lib/python3/dist-packages/smartcard/CardConnection.py", line 146, in transmit
    data, sw1, sw2 = self.doTransmit(bytes, protocol)
  File "/usr/lib/python3/dist-packages/smartcard/pcsc/PCSCCardConnection.py", line 205, in doTransmit
    sw1 = (response[-2] + 256) % 256
IndexError: list index out of range

Also YubiKey Personalization Tool and Yubico Authenticator can no longer find the device.

How can I restore the device and make it work again?

Expected result
---

The usual results like when the device was working normally.

Actual results and logs
---

described above

Other info
---

I tried to send this message through the support form on the yubico
website. But with all browsers I tried, I got the following error:

Failed to accept submission. This could be due to an addon in your
browser or a server error. Please try again with addons disabled. Error
code: 2kzgag-S360000433039

I don't have any addons on my browsers.

**Comment by dainnilsson** [comment]
Would you be able to download and run the latest ykman 4.0 alpha release? You can get a build for Ubuntu here: https://github.com/Yubico/yubikey-manager/actions/runs/578724174 (the ykman-builds-ubuntu artifact near the bottom). It's a zip containing a single stand-alone binary. If you extract it and run `./ykman-4.0.0a3 --diagnose` (with your YubiKey plugged in) and copy the output here that may give us some clues.

Regarding the support form, I checked with the support team and they identified the issue as being a `?` entered in the Order ID field. We'll make sure to fix the form validation logic to better handle this case.

**Comment by ulrichard** [comment]
This is what I get:

**Comment by dainnilsson** [comment]
Thanks. It does indeed look like the application is unable to get any response from the YubiKey at all. If you have access to an NFC reader you could try connecting to it over NFC, which might give us more clues. Otherwise I'd recommend opening a new ticket with our support, they should be able to help!

**Comment by dainnilsson** [comment]
Closing due to inactivity.
