### ISSUE TITLE
"ykman fido list": list_devices take 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by steven-omaha** [Yubico/yubikey-manager#413]
- YubiKey Manager (ykman) version:  3.1.2
- How was it installed?: via Arch linux official repository
- Operating system and version: Arch Linux, latest
- YubiKey model and version: YubiKey 5 NFC, Firmware 5.2.4
- Bug description summary: `ykman fido list` fails

Steps to reproduce
---
1. Insert YubiKey
2. verify it's recognized with `ykman list`
3. run `ykman fido list`

Expected result
---

show output of the command

Actual results and logs
---
```
/usr/lib/python3.9/site-packages/ykman/opgp.py:40: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_to_bytes, int_from_bytes
/usr/lib/python3.9/site-packages/ykman/piv.py:39: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_to_bytes, int_from_bytes
Traceback (most recent call last):
  File "/usr/bin/ykman", line 33, in <module>
    sys.exit(load_entry_point('yubikey-manager==3.1.2', 'console_scripts', 'ykman')())
  File "/usr/lib/python3.9/site-packages/ykman/cli/__main__.py", line 273, in main
    cli(obj={})
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/ykman/cli/fido.py", line 112, in list_creds
    controller = ctx.obj['controller']
  File "/usr/lib/python3.9/site-packages/ykman/cli/util.py", line 127, in __getitem__
    self.resolve()
  File "/usr/lib/python3.9/site-packages/ykman/cli/util.py", line 124, in resolve
    self._objects[k] = f()
  File "/usr/lib/python3.9/site-packages/ykman/cli/__main__.py", line 194, in resolve_device
    dev = _run_cmd_for_single(ctx, subcmd.name, transports, reader)
  File "/usr/lib/python3.9/site-packages/ykman/cli/__main__.py", line 132, in _run_cmd_for_single
    return descriptor.open_device(transports)
  File "/usr/lib/python3.9/site-packages/ykman/descriptor.py", line 96, in open_device
    for drv in _list_drivers(transports):
  File "/usr/lib/python3.9/site-packages/ykman/descriptor.py", line 164, in _list_drivers
    for dev in open_fido():
  File "/usr/lib/python3.9/site-packages/ykman/driver_fido.py", line 97, in open_devices
    for dev in CtapHidDevice.list_devices(descriptor_filter):
TypeError: list_devices() takes 1 positional argument but 2 were given
```

Other info
---
`fido info` fails as well. I assume the fido subcommands are all broken.

**Comment by dainnilsson** [comment]
You have incompatible versions of `yubikey-manager` and `python-fido2` installed, possibly due to the Arch package not correctly enforcing the version requirements (yubikey-manager 3.1.2 requires `fido2 >= 0.7, < 0.9`). You'll need to either upgrade to yubikey-manager >= 4.0 (recommended!) or downgrade `python-fido2` to 0.8 (not recommended!).

**Comment by steven-omaha** [comment]
Thanks for quick reaction!
