### ISSUE TITLE
ykman oath freezes, only way back in is after reboot.

### ISSUE THREAD

**Issue by bushong1** [Yubico/yubikey-manager#415]
- YubiKey Manager (ykman) version: 4.0.2
- How was it installed?: ubuntu apt
- Operating system and version: Ubuntu 20.04
- YubiKey model and version: 5C NFC
- Bug description summary:

Similar symptoms as #367, but i'm on v4.0.2

Steps to reproduce
---

Reboot system, `ykman oath ...` works fine once or twice.  Shortly after, if I try to get another MFA token, it will simply freeze before prompting me to tap the YK.  It won't unfreeze and won't produce any other messages; Ctrl-C won't work, and the only way out is to use another shell to `killall ykman`.  After a few times of doing this, it will stop freezing entirely, and spit out a stack trace saying unable to connecto protocol T0 or T1 (trace below)

Expected result
---

Typical prompting of tap, then provide MFA token with oauth.  This has worked without issue for a week or two.

Actual results and logs
---

```
$ ykman oath accounts code --single <account>
Traceback (most recent call last):
  File "/usr/bin/ykman", line 11, in <module>
    load_entry_point('ykman==4.0.2', 'console_scripts', 'ykman')()
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/ykman/cli/__main__.py", line 367, in main
    cli(obj={})
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/ykman/cli/oath.py", line 575, in code
    _init_session(ctx, password, remember)
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/ykman/cli/oath.py", line 155, in _init_session
    session = ctx.obj["session"]
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/ykman/cli/util.py", line 162, in __getitem__
    self.resolve()
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/ykman/cli/util.py", line 159, in resolve
    self._objects[k] = f()
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/ykman/cli/__main__.py", line 295, in <lambda>
    ctx.obj.add_resolver("conn", lambda: resolve()[0])
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/ykman/cli/__main__.py", line 290, in resolve
    items = _run_cmd_for_single(ctx, subcmd.name, connections, reader)
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/ykman/cli/__main__.py", line 186, in _run_cmd_for_single
    return retrying_connect(None, connections, state=state)
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/ykman/cli/__main__.py", line 87, in retrying_connect
    return connect_to_device(serial, connections)
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/ykman/device.py", line 167, in connect_to_device
    conn = dev.open_connection(connection_type)
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/ykman/pcsc/__init__.py", line 87, in open_connection
    return self._open_smartcard_connection()
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/ykman/pcsc/__init__.py", line 99, in _open_smartcard_connection
    raise e
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/ykman/pcsc/__init__.py", line 95, in _open_smartcard_connection
    return ScardSmartCardConnection(self.reader.createConnection())
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/ykman/pcsc/__init__.py", line 105, in __init__
    connection.connect()
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/smartcard/CardConnectionDecorator.py", line 54, in connect
    self.component.connect(protocol, mode, disposition)
  File "/opt/venvs/yubikey-manager/lib/python3.8/site-packages/smartcard/pcsc/PCSCCardConnection.py", line 123, in connect
    raise CardConnectionException(
smartcard.Exceptions.CardConnectionException: Unable to connect with protocol: T0 or T1. Reader is unavailable.
```

Other info
---

I'm using this in conjunction with `aws-vault`, but also have the recent failures without it.

**Comment by yuriipolishchuk** [comment]
Had similar issue with ykman and aws-vault. Resolved by disabling and enabling PIV interface in Yubikey Manager UI app.

**Comment by adueppen** [comment]
I seem to be having a similar issue, I've tried unloading my yubikey in Firefox as well as adding a `disable-in: firefox` line in `/usr/share/p11-kit/modules/opensc.module`. This fixed a different issue I was having, but ykman still freezes after I visit a website that's checking for PIV. Running it with `--log-level DEBUG` doesn't help very much as it only logs the basic environment info before freezing. Adding `--diagnose` makes it freeze before even printing that. Is there a better way to try to diagnose this?
