### ISSUE TITLE
OTP static password crash

### ISSUE THREAD

**Issue by 1ricardo** [Yubico/yubikey-manager#417]
- YubiKey Manager (ykman) version: yubikey-manager  4.0.2
- How was it installed?: by PIP
- Operating system and version: ArchLinux 64bit 5.12.2-zen2-1-zen
- YubiKey model and version: Yubikey 5 NFC
- Bug description summary: I'm not able to set the OTP static password

Steps to reproduce
---

After executing this command it crashes every time 

```sh
❯ ykman otp static 2
Traceback (most recent call last):
File "/home/rtkocz/.local/bin/ykman", line 8, in <module>
sys.exit(main())
File "/home/rtkocz/.local/lib/python3.9/site-packages/ykman/cli/__main__.py", line 367, in main
cli(obj={})
File "/usr/lib/python3.9/site-packages/click/core.py", line 1134, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python3.9/site-packages/click/core.py", line 1059, in main
rv = self.invoke(ctx)
File "/usr/lib/python3.9/site-packages/click/core.py", line 1665, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/lib/python3.9/site-packages/click/core.py", line 1663, in invoke
sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
File "/usr/lib/python3.9/site-packages/click/core.py", line 927, in make_context
self.parse_args(ctx, args)
File "/usr/lib/python3.9/site-packages/click/core.py", line 1376, in parse_args
value, args = param.handle_parse_result(ctx, opts, args)
File "/usr/lib/python3.9/site-packages/click/core.py", line 2352, in handle_parse_result
value = self.process_value(ctx, value)
File "/usr/lib/python3.9/site-packages/click/core.py", line 2308, in process_value
value = self.type_cast_value(ctx, value)
File "/usr/lib/python3.9/site-packages/click/core.py", line 2295, in type_cast_value
return convert(value)
File "/usr/lib/python3.9/site-packages/click/types.py", line 75, in __call__
return self.convert(value, param, ctx)
File "/home/rtkocz/.local/lib/python3.9/site-packages/ykman/cli/util.py", line 58, in convert
name = super(EnumChoice, self).convert(value, param, ctx).replace("-", "_")
File "/usr/lib/python3.9/site-packages/click/types.py", line 278, in convert
normed_value = normed_value.casefold()
AttributeError: 'KEYBOARD_LAYOUT' object has no attribute 'casefold'
```

my locale

```sh
❯ localectl
System Locale: LANG=en_US.UTF-8
LC_TIME=pl_PL.UTF-8
VC Keymap: pl2
X11 Layout: pl
```

Expected result
---
I would like to use OTP static password

Actual results and logs
---
I think the above log explains everything 

Other info
---
Before I execute the command `ykman otp hotp 2` with success

**Comment by dainnilsson** [comment]
Can you check which version of `click` is installed (via `pip list`)? The yubikey-manager package requires click 6 or 7, and hasn't yet been tested with click 8. Installing yubikey-manager via pip should make sure you have the correct version installed, but it's possible something else has upgraded `click` after this.

**Comment by 1ricardo** [comment]
Yes, you are right, that was `click` after downgrade to `click-7.1.2` it working correctly. Interesting was that I had installed two versions of yubikey-manager and probably that caused all the mess here 

```sh
yubikey-manager 4.0.2
    fido2<1.0,>=0.9
    pyscard<3.0,>=1.9
    pyOpenSSL>=0.15.1
    click<8.0,>=6.0
    cryptography<4.0,>=2.1
yubikey-manager 3.1.2
    fido2<0.9,>=0.7
    pyopenssl
    cryptography
    click
    pyusb
    pyscard
    six
   ```
   
   Thank you for help.

**Comment by 1ricardo** [comment]
If I can ask you, do you consider port yubikey-manager to GoLang ? 
The dependency problem will go away, I tell you from my experience ;)

**Comment by dainnilsson** [comment]
Thanks for confirming! ykman 4.0.3 is now released with compatibility for click 8 added.
We have no current plans to port this project to Go.
