### ISSUE TITLE
yubikit.core.smartcard.ApduError and smartcard.Exceptions.CardConnectionException

### ISSUE THREAD

**Issue by scalp42** [Yubico/yubikey-manager#418]
- YubiKey Manager (ykman) version: `4.0.2`
- How was it installed: `brew install ykman`
- Operating system and version: `MacOS 10.14.6`
- YubiKey model and version: YubiKey 5C Nano, fw `5.2.4`
- Bug description summary:

Multiple stacktraces happen when running Terraform configured to use AWS profile with `aws-vault`.

Steps to reproduce
---

I can't reproduce by running `ykman` commands directly.

I have `~/.aws` set up with following:

```
[profile anthony_scalisi]
region = us-west-2
mfa_serial = arn:aws:iam::xxxxx:mfa/anthony_scalisi

[profile bridge]
include_profile = anthony_scalisi
credential_process = aws-vault exec bridge --mfa-token=$(ykman oath accounts code -s anthony_scalisi@bridge) --duration=1h --json
```

```
provider "aws" {
  alias  = "us-west-2"
  region = "us-west-2"

  profile             = "bridge"
  allowed_account_ids = ["xxxxx"]
}
```

I can run the commands fine by itself:

```
$> ykman oath accounts code -s anthony_scalisi@bridge
977030
```

```
$> aws-vault exec bridge --mfa-token=$(ykman oath accounts code -s anthony_scalisi@bridge) --duration=1h --json

{"Version":1,"AccessKeyId":"xxx","SecretAccessKey":"xxx++23KGPl7zo","SessionToken":"xxxx","Expiration":"2021-05-13T08:11:09Z"}
```

But running `terraform apply` somehow triggers the python stacktrace but still work either way.

Actual results and logs
---

<details>
<summary>Terraform run outout</summary>

```
$> terraform apply

Traceback (most recent call last):
  File "/usr/local/bin/ykman", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/ykman/cli/__main__.py", line 367, in main
    cli(obj={})
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/ykman/cli/oath.py", line 578, in code
    entries = session.calculate_all()
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/yubikit/oath.py", line 383, in calculate_all
    self.protocol.send_apdu(
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/yubikit/core/smartcard.py", line 177, in send_apdu
    raise ApduError(response, sw)
yubikit.core.smartcard.ApduError: APDU error: SW=0x6d00


module.keypair.aws_key_pair.terraform: Refreshing state... [id=terraform]
module.guardduty.aws_guardduty_detector.prod: Refreshing state... [id=cca1586aa41d42c0877c7be8cb6bd2e6]
aws_ebs_encryption_by_default.prod_ebs_encryption: Refreshing state... [id=terraform-20200113215945959800000001]

Traceback (most recent call last):
  File "/usr/local/bin/ykman", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/ykman/cli/__main__.py", line 367, in main
    cli(obj={})
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/ykman/cli/oath.py", line 575, in code
    _init_session(ctx, password, remember)
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/ykman/cli/oath.py", line 155, in _init_session
    session = ctx.obj["session"]
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/ykman/cli/util.py", line 162, in __getitem__
    self.resolve()
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/ykman/cli/util.py", line 159, in resolve
    self._objects[k] = f()
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/ykman/cli/__main__.py", line 295, in <lambda>
    ctx.obj.add_resolver("conn", lambda: resolve()[0])
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/ykman/cli/__main__.py", line 290, in resolve
    items = _run_cmd_for_single(ctx, subcmd.name, connections, reader)
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/ykman/cli/__main__.py", line 186, in _run_cmd_for_single
    return retrying_connect(None, connections, state=state)
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/ykman/cli/__main__.py", line 87, in retrying_connect
    return connect_to_device(serial, connections)
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/ykman/device.py", line 172, in connect_to_device
    info = read_info(dev.pid, conn)
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/ykman/device.py", line 393, in read_info
    info = _read_info_ccid(conn, key_type, interfaces)
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/ykman/device.py", line 229, in _read_info_ccid
    return mgmt.read_device_info()
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/yubikit/management.py", line 424, in read_device_info
    return DeviceInfo.parse(self.backend.read_config(), self.version)
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/yubikit/management.py", line 366, in read_config
    return self.protocol.send_apdu(0, INS_READ_CONFIG, 0, 0)
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/yubikit/core/smartcard.py", line 158, in send_apdu
    response, sw = self.connection.send_and_receive(
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/ykman/pcsc/__init__.py", line 119, in send_and_receive
    data, sw1, sw2 = self.connection.transmit(list(apdu))
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/smartcard/CardConnectionDecorator.py", line 82, in transmit
    return self.component.transmit(bytes, protocol)
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/smartcard/CardConnection.py", line 146, in transmit
    data, sw1, sw2 = self.doTransmit(bytes, protocol)
  File "/usr/local/Cellar/ykman/4.0.2/libexec/lib/python3.9/site-packages/smartcard/pcsc/PCSCCardConnection.py", line 200, in doTransmit
    raise CardConnectionException(
smartcard.Exceptions.CardConnectionException: Failed to transmit with protocol T1. Card was reset.

module.kms.aws_kms_key.quay: Refreshing state... [id=7b83ddaa-8cd8-441e-8416-64d5b991cd20]
module.kms.aws_kms_alias.quay: Refreshing state... [id=alias/quay-20211230211834957500000001]
module.kms.aws_iam_policy.quay_kms: Refreshing state... [id=arn:aws:iam::xxxx:policy/core_usw2_quay_kms]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```
</details>

A bit confused how to trigger it by hand but it happens every time I run Terraform.

**Comment by dainnilsson** [comment]
I'm not too familiar with Terraform, but my guess based on what you've provided is that the command is getting invoked multiple times in parallel, causing commands to interfere with each other. Perhaps the configuration file is being parsed multiple times when the `apply` command is run?

**Comment by dainnilsson** [comment]
Closing due to inactivity.
