### ISSUE TITLE
ykman commands fail consistently in MacOS Big Sur

### ISSUE THREAD

**Issue by sarathmenon** [Yubico/yubikey-manager#422]
- YubiKey Manager (ykman) version: 4.0.3
- How was it installed?: Homebrew, but the download from  https://www.yubico.com/support/download/yubikey-manager/ fails identically.
- Operating system and version: Mac OS Big Sur
- YubiKey model and version: YubiKey NEO, 3.4.9
- Bug description summary:

Certain ykman piv commands fail consistently in Big Sur. I can confirm that `ykman piv reset` and `ykman piv info` consistently fail across multiple machines and multiple yubikeys. This has been tested only on Intel macbooks that were previously on earlier MacOS versions.

Steps to reproduce
---

Install/Upgrade Mac OS to Big Sur.
Run `ykman piv info` on a yubikey that has a certificate loaded, or run `ykman piv reset -f` on a fresh yubikey

Expected result
---

Some valid output

Actual results and logs
---
```
srm SarathsMBP4090:/tmp $ ykman piv info
Traceback (most recent call last):
  File "/usr/local/bin/ykman", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/ykman/cli/__main__.py", line 371, in main
    cli(obj={})
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/ykman/cli/piv.py", line 198, in info
    click.echo(get_piv_info(ctx.obj["session"]))
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/ykman/piv.py", line 428, in get_piv_info
    pin_data = session.get_pin_metadata()
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/yubikit/piv.py", line 576, in get_pin_metadata
    return self._get_pin_puk_metadata(PIN_P2)
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/yubikit/piv.py", line 771, in _get_pin_puk_metadata
    data = Tlv.parse_dict(self.protocol.send_apdu(0, INS_GET_METADATA, 0, p2))
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/yubikit/core/smartcard.py", line 177, in send_apdu
    raise ApduError(response, sw)
yubikit.core.smartcard.ApduError: APDU error: SW=0x6d00
srm SarathsMBP4090:/tmp $ ykman piv reset -f
Resetting PIV data...
Traceback (most recent call last):
  File "/usr/local/bin/ykman", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/ykman/cli/__main__.py", line 371, in main
    cli(obj={})
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/ykman/cli/piv.py", line 218, in reset
    ctx.obj["session"].reset()
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/yubikit/piv.py", line 459, in reset
    counter = self.get_pin_attempts()
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/yubikit/piv.py", line 548, in get_pin_attempts
    return self.get_pin_metadata().attempts_remaining
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/yubikit/piv.py", line 576, in get_pin_metadata
    return self._get_pin_puk_metadata(PIN_P2)
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/yubikit/piv.py", line 771, in _get_pin_puk_metadata
    data = Tlv.parse_dict(self.protocol.send_apdu(0, INS_GET_METADATA, 0, p2))
  File "/usr/local/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/yubikit/core/smartcard.py", line 177, in send_apdu
    raise ApduError(response, sw)
yubikit.core.smartcard.ApduError: APDU error: SW=0x6d00
```

Other info
---

Other commands work, for instance `ykman piv certificates export 9d /tmp/mycert.pem` or `ykman info`

**Comment by dainnilsson** [comment]
Can you try running `ykman apdu -a piv fd` and pasting the output here? That should get the PIV applet version which should help in troubleshooting this.

**Comment by sarathmenon** [comment]
Hi @dainnilsson, this is the output from my laptop:
```
srm SarathsMBP4090:/tmp $ ykman apdu -a piv fd
SELECT AID: A0 00 00 03 08
RECV (SW=9000):
61 11 4F 06 00 00 10 00 01 00 79 07 4F 05 A0 00   a·O·······y·O···
00 03 08                                          ···

SEND: 00 FD 00 00
RECV (SW=9000):
00 01 04                                          ···
```

**Comment by dainnilsson** [comment]
Thanks! I've identified the issue and will make sure it gets fixed in the next release.

**Comment by dainnilsson** [comment]
As a workaround for now, you can edit `/opt/homebrew/Cellar/ykman/4.0.3/libexec/lib/python3.9/site-packages/yubikit/piv.py` on your local machine and make this change to it: https://github.com/Yubico/yubikey-manager/commit/59a71affcd6ee9fb5b36739fd22297dd3b9d2cee#diff-07d95807c3da6acc3d6a9c2247b6f07a8345bb2153cb0452bf07ceaf29c14fa1

**Comment by sarathmenon** [comment]
Thank you! I can confirm that applying the patch fixes my issue

**Comment by dainnilsson** [comment]
4.0.5 is now released which contains the fix.
