### ISSUE TITLE
ykman otp delete fails on macOS 12.3.1

### ISSUE THREAD

**Issue by archoversight** [Yubico/yubikey-manager#505]
- YubiKey Manager (ykman) version: 4.0.8
- How was it installed?: home-brew
- Operating system and version: macOS 12.3.1
- YubiKey model and version: YubiKey 5 NFC (Firmware version: 5.4.2)
- Bug description summary:

```
ykman otp delete 2
```

fails with traceback:

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/ykman/cli/__main__.py", line 104, in retrying_connect
    _, state = _scan_changes(state)
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/ykman/cli/__main__.py", line 91, in _scan_changes
    raise TimeoutError("Timed out waiting for state change")
TimeoutError: Timed out waiting for state change

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/ykman", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/ykman/cli/__main__.py", line 378, in main
    cli(obj={})
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/ykman/cli/otp.py", line 263, in delete
    session = ctx.obj["session"]
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/ykman/cli/util.py", line 164, in __getitem__
    self.resolve()
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/ykman/cli/util.py", line 161, in resolve
    self._objects[k] = f()
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/ykman/cli/__main__.py", line 306, in <lambda>
    ctx.obj.add_resolver("conn", lambda: resolve()[0])
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/ykman/cli/__main__.py", line 299, in resolve
    items = _run_cmd_for_serial(subcmd.name, connections, device)
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/ykman/cli/__main__.py", line 136, in _run_cmd_for_serial
    return retrying_connect(serial, connections)
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/ykman/cli/__main__.py", line 107, in retrying_connect
    raise e
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/ykman/cli/__main__.py", line 97, in retrying_connect
    return connect_to_device(serial, connections)
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/ykman/device.py", line 216, in connect_to_device
    conn = dev.open_connection(connection_type)
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/ykman/hid/base.py", line 50, in open_connection
    return self._connection_cls(self.path)
  File "/opt/homebrew/Cellar/ykman/4.0.8_1/libexec/lib/python3.10/site-packages/ykman/hid/macos.py", line 185, in __init__
    raise OSError(f"Failed to open device for communication: {result}")
OSError: Failed to open device for communication: -536870174
```

Steps to reproduce
---

```
ykman otp delete 2
```

Expected result
---

For it to delete slot 2 in the OTP

Actual results and logs
---

Traceback, see above

Other info
---

N/A

**Comment by dainnilsson** [comment]
This looks like the same issue as in #452. See also #459 .
