### ISSUE TITLE
yubikey-manager 4.0.8 incompatible with click 6.x

### ISSUE THREAD

**Issue by cblessing24** [Yubico/yubikey-manager#509]
- YubiKey Manager (ykman) version: 4.0.8
- How was it installed?: `pacman -S yubikey-manager`
- Operating system and version: Linux 5.18.3-arch1-1
- YubiKey model and version: N/A
- Bug description summary: `TypeError` when invoking `ykman`

Steps to reproduce
---

1. Install yubikey-manager version 4.0.8 and click version 6.x
2. Invoke `ykman` on command line

Expected result
---

No error.

Actual results and logs
---

Error:
```bash
Traceback (most recent call last):
  File "/usr/bin/ykman", line 33, in <module>
    sys.exit(load_entry_point('yubikey-manager==4.0.8', 'console_scripts', 'ykman')())
  File "/usr/bin/ykman", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/ykman/cli/__main__.py", line 48, in <module>
    from .util import YkmanContextObject, ykman_group, cli_fail
  File "/usr/lib/python3.10/site-packages/ykman/cli/util.py", line 139, in <module>
    type=click.Choice(["PEM", "DER"], case_sensitive=False),
TypeError: Choice.__init__() got an unexpected keyword argument 'case_sensitive'
```

**Comment by cblessing24** [comment]
Okay this is not a general problem with yubikey-manager on Arch. My environment was just messed up and using click version 6.6 instead of version 8.1.3 (which was also installed).

That said yubikey-manager seems to want to support click version 6.6 and it does not.

**Comment by dainnilsson** [comment]
Patch release 4.0.9 now requires Click 7 or greater.
