### ISSUE TITLE
`ykman fido info` cannot unpack non-iterable int object

### ISSUE THREAD

**Issue by timfallmk** [Yubico/yubikey-manager#516]
- YubiKey Manager (ykman) version:
`ykman` `4.0.9`
- How was it installed?:
Homebrew
- Operating system and version:
macOS: `12.5`
Python: `3.9.13`
- YubiKey model and version:
5 BIO C (FIDO)
- Bug description summary:
Running `ykman fido info` results in the following error and traceback:
```python
ykman fido info
PIN is set, with 8 attempt(s) remaining.
Traceback (most recent call last):
  File "/opt/homebrew/bin/ykman", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Cellar/ykman/4.0.9/libexec/lib/python3.10/site-packages/ykman/cli/__main__.py", line 378, in main
    cli(obj={})
  File "/opt/homebrew/Cellar/ykman/4.0.9/libexec/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Cellar/ykman/4.0.9/libexec/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Cellar/ykman/4.0.9/libexec/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Cellar/ykman/4.0.9/libexec/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Cellar/ykman/4.0.9/libexec/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Cellar/ykman/4.0.9/libexec/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/ykman/4.0.9/libexec/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/homebrew/Cellar/ykman/4.0.9/libexec/lib/python3.10/site-packages/ykman/cli/fido.py", line 125, in info
    uv_retries, _ = client_pin.get_uv_retries()
TypeError: cannot unpack non-iterable int object
```

This seems likely related to a number of other bugs, with the root cause being python library version upgrades in macOS 12.5

Steps to reproduce
---
1. Plug in YK
2. Run `ykman fido info`

Expected result
---
_FIDO2 general output information)_

Actual results and logs
_(See above)_

Other info
---
Certain nested commands do work, e.g. `ykman fido credentials list`

**Comment by dainnilsson** [comment]
ykman 5.0 is now released, which fixes this issue.
