### ISSUE TITLE
ykman otp info - Failed to connect to the device

### ISSUE THREAD

**Issue by tekumara** [Yubico/yubikey-manager#537]
- YubiKey Manager (ykman) version: 5.0.0
- How was it installed?: brew install ykman
- Operating system and version: macos ventura
- YubiKey model and version: YubiKey 5C Nano 5.4.3

Steps to reproduce
---

❯ ykman otp info
WARNING: Failed opening device
WARNING: Failed opening device
WARNING: Failed opening device
WARNING: Failed opening device
WARNING: Failed opening device
WARNING: Failed opening device
WARNING: Failed opening device
ERROR: Failed to connect to the device

**Comment by feralbob** [comment]
Confirmed same results on `5.0.1`

```
➜  yubikey which ykman
/usr/local/bin/ykman
➜  yubikey ykman --version
YubiKey Manager (ykman) version: 5.0.1
➜  yubikey ykman otp info
WARNING: Failed opening device
WARNING: Failed opening device
WARNING: Failed opening device
WARNING: Failed opening device
WARNING: Failed opening device
WARNING: Failed opening device
WARNING: Failed opening device
ERROR: Failed to connect to the device
➜  yubikey 
```

Version 4.0.7 - fails for me too

```
➜  yubikey /Applications/YubiKey\ Manager.app/Contents/MacOS/ykman --version
YubiKey Manager (ykman) version: 4.0.7
➜  yubikey /Applications/YubiKey\ Manager.app/Contents/MacOS/ykman otp info 
qml: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/cli/__main__.py", line 104, in retrying_connect
    _, state = _scan_changes(state)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/cli/__main__.py", line 91, in _scan_changes
    raise TimeoutError("Timed out waiting for state change")

TimeoutError: Timed out waiting for state change


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "qrc:///py/cli.py", line 12, in run
    return main()

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/cli/__main__.py", line 378, in main
    cli(obj={})

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/cli/otp.py", line 186, in info
    session = ctx.obj["session"]

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/cli/util.py", line 164, in __getitem__
    self.resolve()

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/cli/util.py", line 161, in resolve
    self._objects[k] = f()

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/cli/__main__.py", line 306, in <lambda>
    ctx.obj.add_resolver("conn", lambda: resolve()[0])

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/cli/__main__.py", line 301, in resolve
    items = _run_cmd_for_single(ctx, subcmd.name, connections, reader)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/cli/__main__.py", line 197, in _run_cmd_for_single
    return retrying_connect(None, connections, state=state)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/cli/__main__.py", line 107, in retrying_connect
    raise e

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/cli/__main__.py", line 97, in retrying_connect
    return connect_to_device(serial, connections)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/device.py", line 216, in connect_to_device
    conn = dev.open_connection(connection_type)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/hid/base.py", line 50, in open_connection
    return self._connection_cls(self.path)

  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ykman/hid/macos.py", line 185, in __init__
    raise OSError(f"Failed to open device for communication: {result}")

OSError: Failed to open device for communication: -536870174

```

**Comment by dainnilsson** [comment]
Can you try running `ykman --diagnose` and providing the output here?

**Comment by feralbob** [comment]
Yes - granting that permission resulted in the command working fine. I wonder if there is a way to query if a particular permission has been granted or not.

**Comment by tekumara** [comment]
thank you that works!

why does `otp info` require this permission though?

i think i'd prefer not to have to give all applications that run in the terminal the ability to monitor input just so I can see the otp info.

**Comment by dainnilsson** [comment]
I'm glad this resolved the issue!

> why does `otp info` require this permission though?

The permission is required to be able to connect to the YubiKey over the USB OTP interface, which is the one used when the YubiKey acts as a keyboard to output a Yubico OTP. Since the YubiKey shows up as a keyboard, access to this interface is covered by this permission on MacOS.
