### ISSUE TITLE
When generating a self-signed certificate for slot 9c, APDU error 0x6982 is reported

### ISSUE THREAD

**Issue by foxiagouhe** [Yubico/yubikey-manager#550]
- YubiKey Manager (ykman) version: 5.0.2-dev.0
- How was it installed?: install from source (poetry run)
- Operating system and version: macOS Monterey 12.6.3
- YubiKey model and version: YubiKey 5C NFC 5.4.3
- Bug description summary: Failed to generate a self-signed certificate for slot 9c, prompting APDU error: SW=0x6982, slot9a and slot 9d can generate self-signed certificates normally

Steps to reproduce
---

`poetry run ykman --log-level DEBUG piv certificates generate -d 365 -s "CN=PIV TEST" 9c public9c.key`

Without changing any source code, slot 9c self-signed certificate generation fails, other slots are normal

Expected result
---

Generate a self-signed certificate normally

Actual results and logs
---
```shell
INFO 20:51:54.512 [ykman.logging.set_log_level:60] Logging at level: DEBUG
WARNING 20:51:54.512 [ykman.logging.set_log_level:64] 
#############################################################################
#                                                                           #
# WARNING: Sensitive data may be logged!                                    #
# Some personally identifying information may be logged, such as usernames! #
#                                                                           #
#############################################################################
INFO 20:51:54.512 [ykman._cli.__main__.cli:238] System info:
  ykman:            5.0.2-dev.0
  Python:           3.9.6 (default, Oct 18 2022, 12:41:40) 
[Clang 14.0.0 (clang-1400.0.29.202)]
  Platform:         darwin
  Arch:             x86_64
  System date:      2023-03-27
  Running as admin: False

DEBUG 20:51:54.530 [ykman.device.add:162] Add device for <class 'yubikit.core.smartcard.SmartCardConnection'>: ScardYubiKeyDevice(pid=0404, fingerprint='Yubico YubiKey CCID')
DEBUG 20:51:54.534 [yubikit.support.read_info:261] Attempting to read device info, using ScardSmartCardConnection
DEBUG 20:51:54.535 [yubikit.management.__init__:443] Management session initialized for connection=ScardSmartCardConnection, version=5.4.3
DEBUG 20:51:54.536 [yubikit.support.read_info:289] Read info: DeviceInfo(config=DeviceConfig(enabled_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.PIV|OPENPGP: 24>, <TRANSPORT.NFC: 'nfc'>: <CAPABILITY.PIV|OPENPGP: 24>}, auto_eject_timeout=0, challenge_response_timeout=15, device_flags=<DEVICE_FLAG.0: 0>), serial=xxxxxx, version=Version(major=5, minor=4, patch=3), form_factor=<FORM_FACTOR.USB_C_KEYCHAIN: 3>, supported_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.FIDO2|HSMAUTH|OATH|PIV|OPENPGP|4|U2F|OTP: 831>, <TRANSPORT.NFC: 'nfc'>: <CAPABILITY.FIDO2|HSMAUTH|OATH|PIV|OPENPGP|4|U2F|OTP: 831>}, is_locked=False, is_fips=False, is_sky=False)
DEBUG 20:51:54.537 [yubikit.support.read_info:348] Device info, after tweaks: DeviceInfo(config=DeviceConfig(enabled_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.PIV|OPENPGP: 24>, <TRANSPORT.NFC: 'nfc'>: <CAPABILITY.PIV|OPENPGP: 24>}, auto_eject_timeout=0, challenge_response_timeout=15, device_flags=<DEVICE_FLAG.0: 0>), serial=xxxxxx, version=Version(major=5, minor=4, patch=3), form_factor=<FORM_FACTOR.USB_C_KEYCHAIN: 3>, supported_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.FIDO2|HSMAUTH|OATH|PIV|OPENPGP|4|U2F|OTP: 831>, <TRANSPORT.NFC: 'nfc'>: <CAPABILITY.FIDO2|HSMAUTH|OATH|PIV|OPENPGP|4|U2F|OTP: 831>}, is_locked=False, is_fips=False, is_sky=False)
DEBUG 20:51:54.538 [ykman.device.add:173] Resolved device xxxxxx
DEBUG 20:51:54.543 [yubikit.core.smartcard.enable_touch_workaround:150] Touch workaround enabled=False
DEBUG 20:51:54.543 [yubikit.piv.__init__:450] PIV session initialized (version=5.4.3)
DEBUG 20:51:54.543 [ykman.piv.get_pivman_data:241] Reading pivman data
DEBUG 20:51:54.544 [yubikit.piv.get_object:684] Reading data from object slot 0x5fff00
DEBUG 20:51:54.544 [ykman.piv.get_pivman_data:247] No data, initializing blank
DEBUG 20:51:54.545 [ykman._cli.util.click_prompt:219] Input requested (Enter a management key [blank to use default key])
DEBUG 20:51:54.545 [ykman._cli.util.click_prompt:228] Using interactive prompt...
Enter a management key [blank to use default key]: 
DEBUG 20:51:56.45 [yubikit.piv.get_management_key_metadata:608] Getting management key metadata
DEBUG 20:51:56.47 [yubikit.piv.authenticate:491] Authenticating with key type: 3
DEBUG 20:51:56.55 [ykman._cli.util.click_prompt:219] Input requested (Enter PIN)
DEBUG 20:51:56.55 [ykman._cli.util.click_prompt:228] Using interactive prompt...
Enter PIN: 
DEBUG 20:51:58.289 [yubikit.piv.verify_pin:548] Verifying PIN
DEBUG 20:51:58.307 [yubikit.piv.get_slot_metadata:622] Getting metadata for slot 9C (SIGNATURE)
DEBUG 20:51:58.310 [ykman.piv.generate_self_signed_certificate:634] Generating a self-signed certificate
DEBUG 20:51:58.311 [ykman.piv.sign_certificate_builder:562] Signing a certificate
DEBUG 20:51:58.322 [yubikit.piv.sign:644] Signing data with key in slot 9C (SIGNATURE) of type 20 using hash=<cryptography.hazmat.primitives.hashes.SHA256 object at 0x1027c4970>, padding=<cryptography.hazmat.primitives.asymmetric.padding.PKCS1v15 object at 0x1027c4c40>
ERROR 20:51:58.327 [ykman._cli.__main__.main:380] Certificate generation failed.
Traceback (most recent call last):
  File "/xxx/yubikey-manager/ykman/_cli/piv.py", line 950, in generate_certificate
    cert = generate_self_signed_certificate(
  File "/xxx/yubikey-manager/ykman/piv.py", line 649, in generate_self_signed_certificate
    return sign_certificate_builder(session, slot, key_type, builder, hash_algorithm)
  File "/xxx/yubikey-manager/ykman/piv.py", line 566, in sign_certificate_builder
    sig = session.sign(
  File "/xxx/yubikey-manager/yubikit/piv.py", line 649, in sign
    return self._use_private_key(slot, key_type, padded, False)
  File "/xxx/yubikey-manager/yubikit/piv.py", line 846, in _use_private_key
    response = self.protocol.send_apdu(
  File "/xxx/yubikey-manager/yubikit/core/smartcard.py", line 206, in send_apdu
    raise ApduError(response, sw)
yubikit.core.smartcard.ApduError: APDU error: SW=0x6982

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/xxx/yubikey-manager/ykman/_cli/__main__.py", line 364, in main
    cli(obj={})
  File "/xxx/Library/Caches/pypoetry/virtualenvs/yubikey-manager-Y2K6ifkx-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/xxx/Library/Caches/pypoetry/virtualenvs/yubikey-manager-Y2K6ifkx-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/xxx/Library/Caches/pypoetry/virtualenvs/yubikey-manager-Y2K6ifkx-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/xxx/Library/Caches/pypoetry/virtualenvs/yubikey-manager-Y2K6ifkx-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/xxx/Library/Caches/pypoetry/virtualenvs/yubikey-manager-Y2K6ifkx-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/xxx/Library/Caches/pypoetry/virtualenvs/yubikey-manager-Y2K6ifkx-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/xxx/Library/Caches/pypoetry/virtualenvs/yubikey-manager-Y2K6ifkx-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/xxx/Library/Caches/pypoetry/virtualenvs/yubikey-manager-Y2K6ifkx-py3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/xxx/yubikey-manager/ykman/_cli/piv.py", line 956, in generate_certificate
    raise CliFail("Certificate generation failed.")
ykman._cli.util.CliFail: Certificate generation failed.
(yubikey-manager-py3.9) 
```

Other info
---

Check the source code, `SECURITY_CONDITION_NOT_SATISFIED = 0x6982`, it seems that the security conditions are not satisfied, I don't know what security conditions are not satisfied

**Comment by dainnilsson** [comment]
Thank you for the report, I have been able to reproduce this. I believe this is an issue with the default PIN policy of slot 9C and how the `piv certificates generate` command performs the operation. I'll post another update once I've had a chance to investigate it a bit more.

**Comment by dainnilsson** [comment]
This should now be fixed in the latest commit on `main`. We'll try to get a new release out soon, I'll leave the issue open until we do.

**Comment by foxiagouhe** [comment]
> This should now be fixed in the latest commit on `main`. We'll try to get a new release out soon, I'll leave the issue open until we do.

ok, thank !!

**Comment by dainnilsson** [comment]
5.1.0 has now been released with this fix.
