### ISSUE TITLE
smartcard.Exceptions.CardConnectionException: Unable to connect with protocol: T0 or T1. Reader is unavailable.

### ISSUE THREAD

**Issue by Torxed** [Yubico/yubikey-manager#559]
- YubiKey Manager (ykman) version: 5.1.1
- How was it installed?: `pacman -S ykman`
- Operating system and version: Arch Linux
- opensc version: 0.23.0-1
- ccid version: 1.5.2-1
- YubiKey model and version: NFC 5C
- Bug description summary: Whenever I run the Python example codes from https://developers.yubico.com/yubikey-manager/Library_Usage.html - the application errors out in one of it's threads (?) when I remove the yubikey from the machine.

Steps to reproduce
---

Install `ykman`, run for instance:
```python
from ykman.device import list_all_devices, scan_devices
from yubikit.core.smartcard import SmartCardConnection
from time import sleep

handled_serials = set()  # Keep track of YubiKeys we've already handled.
state = None

while True:  # Run this until we stop the script with Ctrl+C
    pids, new_state = scan_devices()
    if new_state != state:
        state = new_state  # State has changed
        for device, info in list_all_devices():
            if info.serial not in handled_serials:  # Unhandled YubiKey
                print(f"Programming YubiKey with serial: {info.serial}")
                ...  # Do something with the device here.
                handled_serials.add(info.serial)
    else:
        sleep(1.0)  # No change, sleep for 1 second.
```

Wait a second for it to be detected, then unplug the Yubikey at any point.

Expected result
---

The code to only print the `print()` message, nothing else.

Actual results and logs
---

Right when I unplug the yubikey:
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ykman/device.py", line 168, in add
    with dev.open_connection(conn_type) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ykman/pcsc/__init__.py", line 88, in open_connection
    return self._open_smartcard_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ykman/pcsc/__init__.py", line 100, in _open_smartcard_connection
    raise e
  File "/usr/lib/python3.11/site-packages/ykman/pcsc/__init__.py", line 96, in _open_smartcard_connection
    return ScardSmartCardConnection(self.reader.createConnection())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ykman/pcsc/__init__.py", line 106, in __init__
    connection.connect()
  File "/usr/lib/python3.11/site-packages/smartcard/CardConnectionDecorator.py", line 54, in connect
    self.component.connect(protocol, mode, disposition)
  File "/usr/lib/python3.11/site-packages/smartcard/pcsc/PCSCCardConnection.py", line 122, in connect
    raise CardConnectionException(
smartcard.Exceptions.CardConnectionException: Unable to connect with protocol: T0 or T1. Reader is unavailable.
Failed opening device
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ykman/device.py", line 168, in add
    with dev.open_connection(conn_type) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ykman/pcsc/__init__.py", line 88, in open_connection
    return self._open_smartcard_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ykman/pcsc/__init__.py", line 100, in _open_smartcard_connection
    raise e
  File "/usr/lib/python3.11/site-packages/ykman/pcsc/__init__.py", line 96, in _open_smartcard_connection
    return ScardSmartCardConnection(self.reader.createConnection())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ykman/pcsc/__init__.py", line 106, in __init__
    connection.connect()
  File "/usr/lib/python3.11/site-packages/smartcard/CardConnectionDecorator.py", line 54, in connect
    self.component.connect(protocol, mode, disposition)
  File "/usr/lib/python3.11/site-packages/smartcard/pcsc/PCSCCardConnection.py", line 122, in connect
    raise CardConnectionException(
smartcard.Exceptions.CardConnectionException: Unable to connect with protocol: T0 or T1. Reader is unavailable.
```

Other info
---

The weird thing for me is that this is triggered "elsewhere"? My code is never referenced in the stack trace. So I have no idea how to mute this with a `try/except`.

My `/etc/opensc.conf` file:
```conf
app default {
	# debug = 3;
	# debug_file = opensc-debug.txt;
	framework pkcs15 {
		# use_file_caching = public;
	}
}
```

**Comment by bencardoen** [comment]
Can confirm this, without the API, when you start the authenticator from the CLI, it will report this as well when you unplug the key.
