### ISSUE TITLE
Smartcard APDU Error SW=0x6a80 when trying add keys or changing OpenPGP admin key

### ISSUE THREAD

**Issue by karlfroldan** [Yubico/yubikey-manager#603]
- YubiKey Manager (ykman) version:
- How was it installed?: `emerge -av app-crypt/yubikey-manager`
- Operating system and version: Gentoo x86-64 - Linux Kernel 6.6.16-gentoo-dist
- YubiKey model and version: YubiKey 5C NFC
- Bug description summary:

Steps to reproduce
---

Try to do any OpenPGP management with ykman.

```bash
sudo rc-service pcscd start

ykman openpgp reset
# WARNING! This will delete all stored OpenPGP keys and data and restore factory settings. Proceed? [y/N]: y
# Resetting OpenPGP data, don't remove the YubiKey...
# Success! All data has been cleared and default PINs are set.
# PIN:         123456
# Reset code:  NOT SET
# Admin PIN:   12345678

ykman openpgp access change-admin-pin
# Enter Admin PIN: ADMIN PIN ABOVE
# New Admin PIN: NEW ADMIN PIN
# Repeat for confirmation: NEW ADMIN PIN
```

Actual results and logs
```
ERROR: An unexpected error has occuredTraceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ykman/_cli/__main__.py", line 377, in main
    cli(obj={})
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ykman/_cli/openpgp.py", line 163, in set_pin_retries
    session.verify_admin(admin_pin)
  File "/usr/lib/python3.11/site-packages/yubikit/openpgp.py", line 1208, in verify_admin
    self._verify(PW.ADMIN, admin_pin)
  File "/usr/lib/python3.11/site-packages/yubikit/openpgp.py", line 1184, in _verify
    raise e
  File "/usr/lib/python3.11/site-packages/yubikit/openpgp.py", line 1179, in _verify
    self.protocol.send_apdu(0, INS.VERIFY, 0, pw + mode, pin_enc)
  File "/usr/lib/python3.11/site-packages/yubikit/core/smartcard.py", line 228, in send_apdu
    raise ApduError(response, sw)
yubikit.core.smartcard.ApduError: APDU error: SW=0x6a80
```

Other Info:

I am able to use my YubiKey on the browser. I just can't import my GPG keys to it.

**Comment by mantono** [comment]
I got almost the exact same issue, except I get it when I try to reset the regular PIN.

- YubiKey Manager (ykman) version: `YubiKey Manager (ykman) version: 5.2.0`
- How was it installed?: `emerge -av app-crypt/yubikey-manager`
- OS & Kernel: `Linux 6.1.12-gentoo-dist x86_64 GNU/Linux`
- YubiKey model and version: YubiKey 5C NFC

```sh
ykman openpgp access unblock-pin
Enter Reset Code:
New PIN:
Repeat for confirmation:
```

```
ERROR: An unexpected error has occuredTraceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ykman/_cli/__main__.py", line 377, in main
    cli(obj={})
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ykman/_cli/openpgp.py", line 296, in unblock_pin
    session.reset_pin(new_pin, reset_code)
  File "/usr/lib/python3.11/site-packages/yubikit/openpgp.py", line 1294, in reset_pin
    raise e
  File "/usr/lib/python3.11/site-packages/yubikit/openpgp.py", line 1287, in reset_pin
    self.protocol.send_apdu(0, INS.RESET_RETRY_COUNTER, p1, PW.USER, data)
  File "/usr/lib/python3.11/site-packages/yubikit/core/smartcard.py", line 228, in send_apdu
    raise ApduError(response, sw)
yubikit.core.smartcard.ApduError: APDU error: SW=0x6983
```

**Comment by dainnilsson** [comment]
Great, sounds like this issue is resolved by using a newer ykman version.
